// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: voice/v1/voice.proto

package voicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Slot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slot) Reset() {
	*x = Slot{}
	mi := &file_voice_v1_voice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_voice_v1_voice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_voice_v1_voice_proto_rawDescGZIP(), []int{0}
}

func (x *Slot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Slot) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ParsedVoiceCommand struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CommandId         string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Intent            string                 `protobuf:"bytes,2,opt,name=intent,proto3" json:"intent,omitempty"`
	RoomId            string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	DeviceId          string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	EntityId          string                 `protobuf:"bytes,5,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	TargetState       string                 `protobuf:"bytes,6,opt,name=target_state,json=targetState,proto3" json:"target_state,omitempty"`
	Confidence        float64                `protobuf:"fixed64,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Slots             []*Slot                `protobuf:"bytes,8,rep,name=slots,proto3" json:"slots,omitempty"`
	RecognizedCommand string                 `protobuf:"bytes,9,opt,name=recognized_command,json=recognizedCommand,proto3" json:"recognized_command,omitempty"`
	ScenarioId        string                 `protobuf:"bytes,10,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	ScenarioName      string                 `protobuf:"bytes,11,opt,name=scenario_name,json=scenarioName,proto3" json:"scenario_name,omitempty"`
	ExecutionStatus   string                 `protobuf:"bytes,12,opt,name=execution_status,json=executionStatus,proto3" json:"execution_status,omitempty"`
	DecisionId        string                 `protobuf:"bytes,13,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ParsedVoiceCommand) Reset() {
	*x = ParsedVoiceCommand{}
	mi := &file_voice_v1_voice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedVoiceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedVoiceCommand) ProtoMessage() {}

func (x *ParsedVoiceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_voice_v1_voice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedVoiceCommand.ProtoReflect.Descriptor instead.
func (*ParsedVoiceCommand) Descriptor() ([]byte, []int) {
	return file_voice_v1_voice_proto_rawDescGZIP(), []int{1}
}

func (x *ParsedVoiceCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ParsedVoiceCommand) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *ParsedVoiceCommand) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ParsedVoiceCommand) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ParsedVoiceCommand) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ParsedVoiceCommand) GetTargetState() string {
	if x != nil {
		return x.TargetState
	}
	return ""
}

func (x *ParsedVoiceCommand) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ParsedVoiceCommand) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *ParsedVoiceCommand) GetRecognizedCommand() string {
	if x != nil {
		return x.RecognizedCommand
	}
	return ""
}

func (x *ParsedVoiceCommand) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *ParsedVoiceCommand) GetScenarioName() string {
	if x != nil {
		return x.ScenarioName
	}
	return ""
}

func (x *ParsedVoiceCommand) GetExecutionStatus() string {
	if x != nil {
		return x.ExecutionStatus
	}
	return ""
}

func (x *ParsedVoiceCommand) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

type ParseVoiceCommandRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Audio          []byte                 `protobuf:"bytes,1,opt,name=audio,proto3" json:"audio,omitempty"`
	EdgeId         string                 `protobuf:"bytes,2,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	RoomId         string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Source         string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	DeferExecution bool                   `protobuf:"varint,5,opt,name=defer_execution,json=deferExecution,proto3" json:"defer_execution,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ParseVoiceCommandRequest) Reset() {
	*x = ParseVoiceCommandRequest{}
	mi := &file_voice_v1_voice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseVoiceCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseVoiceCommandRequest) ProtoMessage() {}

func (x *ParseVoiceCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_v1_voice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseVoiceCommandRequest.ProtoReflect.Descriptor instead.
func (*ParseVoiceCommandRequest) Descriptor() ([]byte, []int) {
	return file_voice_v1_voice_proto_rawDescGZIP(), []int{2}
}

func (x *ParseVoiceCommandRequest) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *ParseVoiceCommandRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *ParseVoiceCommandRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ParseVoiceCommandRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ParseVoiceCommandRequest) GetDeferExecution() bool {
	if x != nil {
		return x.DeferExecution
	}
	return false
}

type ParseVoiceCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *ParsedVoiceCommand    `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseVoiceCommandResponse) Reset() {
	*x = ParseVoiceCommandResponse{}
	mi := &file_voice_v1_voice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseVoiceCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseVoiceCommandResponse) ProtoMessage() {}

func (x *ParseVoiceCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_v1_voice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseVoiceCommandResponse.ProtoReflect.Descriptor instead.
func (*ParseVoiceCommandResponse) Descriptor() ([]byte, []int) {
	return file_voice_v1_voice_proto_rawDescGZIP(), []int{3}
}

func (x *ParseVoiceCommandResponse) GetCommand() *ParsedVoiceCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

type MatchOfflinePhraseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phrase        string                 `protobuf:"bytes,1,opt,name=phrase,proto3" json:"phrase,omitempty"`
	EdgeId        string                 `protobuf:"bytes,2,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchOfflinePhraseRequest) Reset() {
	*x = MatchOfflinePhraseRequest{}
	mi := &file_voice_v1_voice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchOfflinePhraseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchOfflinePhraseRequest) ProtoMessage() {}

func (x *MatchOfflinePhraseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_v1_voice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchOfflinePhraseRequest.ProtoReflect.Descriptor instead.
func (*MatchOfflinePhraseRequest) Descriptor() ([]byte, []int) {
	return file_voice_v1_voice_proto_rawDescGZIP(), []int{4}
}

func (x *MatchOfflinePhraseRequest) GetPhrase() string {
	if x != nil {
		return x.Phrase
	}
	return ""
}

func (x *MatchOfflinePhraseRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *MatchOfflinePhraseRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MatchOfflinePhraseRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type MatchOfflinePhraseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *ParsedVoiceCommand    `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchOfflinePhraseResponse) Reset() {
	*x = MatchOfflinePhraseResponse{}
	mi := &file_voice_v1_voice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchOfflinePhraseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchOfflinePhraseResponse) ProtoMessage() {}

func (x *MatchOfflinePhraseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_v1_voice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchOfflinePhraseResponse.ProtoReflect.Descriptor instead.
func (*MatchOfflinePhraseResponse) Descriptor() ([]byte, []int) {
	return file_voice_v1_voice_proto_rawDescGZIP(), []int{5}
}

func (x *MatchOfflinePhraseResponse) GetCommand() *ParsedVoiceCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

var File_voice_v1_voice_proto protoreflect.FileDescriptor

const file_voice_v1_voice_proto_rawDesc = "" +
	"\n" +
	"\x14voice/v1/voice.proto\x12\bvoice.v1\"0\n" +
	"\x04Slot\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xc8\x03\n" +
	"\x12ParsedVoiceCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06intent\x18\x02 \x01(\tR\x06intent\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tentity_id\x18\x05 \x01(\tR\bentityId\x12!\n" +
	"\ftarget_state\x18\x06 \x01(\tR\vtargetState\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x01R\n" +
	"confidence\x12$\n" +
	"\x05slots\x18\b \x03(\v2\x0e.voice.v1.SlotR\x05slots\x12-\n" +
	"\x12recognized_command\x18\t \x01(\tR\x11recognizedCommand\x12\x1f\n" +
	"\vscenario_id\x18\n" +
	" \x01(\tR\n" +
	"scenarioId\x12#\n" +
	"\rscenario_name\x18\v \x01(\tR\fscenarioName\x12)\n" +
	"\x10execution_status\x18\f \x01(\tR\x0fexecutionStatus\x12\x1f\n" +
	"\vdecision_id\x18\r \x01(\tR\n" +
	"decisionId\"\xa3\x01\n" +
	"\x18ParseVoiceCommandRequest\x12\x14\n" +
	"\x05audio\x18\x01 \x01(\fR\x05audio\x12\x17\n" +
	"\aedge_id\x18\x02 \x01(\tR\x06edgeId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12'\n" +
	"\x0fdefer_execution\x18\x05 \x01(\bR\x0edeferExecution\"S\n" +
	"\x19ParseVoiceCommandResponse\x126\n" +
	"\acommand\x18\x01 \x01(\v2\x1c.voice.v1.ParsedVoiceCommandR\acommand\"}\n" +
	"\x19MatchOfflinePhraseRequest\x12\x16\n" +
	"\x06phrase\x18\x01 \x01(\tR\x06phrase\x12\x17\n" +
	"\aedge_id\x18\x02 \x01(\tR\x06edgeId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"T\n" +
	"\x1aMatchOfflinePhraseResponse\x126\n" +
	"\acommand\x18\x01 \x01(\v2\x1c.voice.v1.ParsedVoiceCommandR\acommand2\xcd\x01\n" +
	"\fVoiceService\x12\\\n" +
	"\x11ParseVoiceCommand\x12\".voice.v1.ParseVoiceCommandRequest\x1a#.voice.v1.ParseVoiceCommandResponse\x12_\n" +
	"\x12MatchOfflinePhrase\x12#.voice.v1.MatchOfflinePhraseRequest\x1a$.voice.v1.MatchOfflinePhraseResponseB'Z%voice-service/pkg/pb/voice/v1;voicev1b\x06proto3"

var (
	file_voice_v1_voice_proto_rawDescOnce sync.Once
	file_voice_v1_voice_proto_rawDescData []byte
)

func file_voice_v1_voice_proto_rawDescGZIP() []byte {
	file_voice_v1_voice_proto_rawDescOnce.Do(func() {
		file_voice_v1_voice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_voice_v1_voice_proto_rawDesc), len(file_voice_v1_voice_proto_rawDesc)))
	})
	return file_voice_v1_voice_proto_rawDescData
}

var file_voice_v1_voice_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_voice_v1_voice_proto_goTypes = []any{
	(*Slot)(nil),                       // 0: voice.v1.Slot
	(*ParsedVoiceCommand)(nil),         // 1: voice.v1.ParsedVoiceCommand
	(*ParseVoiceCommandRequest)(nil),   // 2: voice.v1.ParseVoiceCommandRequest
	(*ParseVoiceCommandResponse)(nil),  // 3: voice.v1.ParseVoiceCommandResponse
	(*MatchOfflinePhraseRequest)(nil),  // 4: voice.v1.MatchOfflinePhraseRequest
	(*MatchOfflinePhraseResponse)(nil), // 5: voice.v1.MatchOfflinePhraseResponse
}
var file_voice_v1_voice_proto_depIdxs = []int32{
	0, // 0: voice.v1.ParsedVoiceCommand.slots:type_name -> voice.v1.Slot
	1, // 1: voice.v1.ParseVoiceCommandResponse.command:type_name -> voice.v1.ParsedVoiceCommand
	1, // 2: voice.v1.MatchOfflinePhraseResponse.command:type_name -> voice.v1.ParsedVoiceCommand
	2, // 3: voice.v1.VoiceService.ParseVoiceCommand:input_type -> voice.v1.ParseVoiceCommandRequest
	4, // 4: voice.v1.VoiceService.MatchOfflinePhrase:input_type -> voice.v1.MatchOfflinePhraseRequest
	3, // 5: voice.v1.VoiceService.ParseVoiceCommand:output_type -> voice.v1.ParseVoiceCommandResponse
	5, // 6: voice.v1.VoiceService.MatchOfflinePhrase:output_type -> voice.v1.MatchOfflinePhraseResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_voice_v1_voice_proto_init() }
func file_voice_v1_voice_proto_init() {
	if File_voice_v1_voice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_voice_v1_voice_proto_rawDesc), len(file_voice_v1_voice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_voice_v1_voice_proto_goTypes,
		DependencyIndexes: file_voice_v1_voice_proto_depIdxs,
		MessageInfos:      file_voice_v1_voice_proto_msgTypes,
	}.Build()
	File_voice_v1_voice_proto = out.File
	file_voice_v1_voice_proto_goTypes = nil
	file_voice_v1_voice_proto_depIdxs = nil
}
