// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: voice/v1/voice.proto

package voicev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VoiceService_ParseVoiceCommand_FullMethodName  = "/voice.v1.VoiceService/ParseVoiceCommand"
	VoiceService_MatchOfflinePhrase_FullMethodName = "/voice.v1.VoiceService/MatchOfflinePhrase"
)

// VoiceServiceClient is the client API for VoiceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoiceServiceClient interface {
	ParseVoiceCommand(ctx context.Context, in *ParseVoiceCommandRequest, opts ...grpc.CallOption) (*ParseVoiceCommandResponse, error)
	MatchOfflinePhrase(ctx context.Context, in *MatchOfflinePhraseRequest, opts ...grpc.CallOption) (*MatchOfflinePhraseResponse, error)
}

type voiceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoiceServiceClient(cc grpc.ClientConnInterface) VoiceServiceClient {
	return &voiceServiceClient{cc}
}

func (c *voiceServiceClient) ParseVoiceCommand(ctx context.Context, in *ParseVoiceCommandRequest, opts ...grpc.CallOption) (*ParseVoiceCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseVoiceCommandResponse)
	err := c.cc.Invoke(ctx, VoiceService_ParseVoiceCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) MatchOfflinePhrase(ctx context.Context, in *MatchOfflinePhraseRequest, opts ...grpc.CallOption) (*MatchOfflinePhraseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchOfflinePhraseResponse)
	err := c.cc.Invoke(ctx, VoiceService_MatchOfflinePhrase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoiceServiceServer is the server API for VoiceService service.
// All implementations must embed UnimplementedVoiceServiceServer
// for forward compatibility.
type VoiceServiceServer interface {
	ParseVoiceCommand(context.Context, *ParseVoiceCommandRequest) (*ParseVoiceCommandResponse, error)
	MatchOfflinePhrase(context.Context, *MatchOfflinePhraseRequest) (*MatchOfflinePhraseResponse, error)
	mustEmbedUnimplementedVoiceServiceServer()
}

// UnimplementedVoiceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVoiceServiceServer struct{}

func (UnimplementedVoiceServiceServer) ParseVoiceCommand(context.Context, *ParseVoiceCommandRequest) (*ParseVoiceCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseVoiceCommand not implemented")
}
func (UnimplementedVoiceServiceServer) MatchOfflinePhrase(context.Context, *MatchOfflinePhraseRequest) (*MatchOfflinePhraseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MatchOfflinePhrase not implemented")
}
func (UnimplementedVoiceServiceServer) mustEmbedUnimplementedVoiceServiceServer() {}
func (UnimplementedVoiceServiceServer) testEmbeddedByValue()                      {}

// UnsafeVoiceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoiceServiceServer will
// result in compilation errors.
type UnsafeVoiceServiceServer interface {
	mustEmbedUnimplementedVoiceServiceServer()
}

func RegisterVoiceServiceServer(s grpc.ServiceRegistrar, srv VoiceServiceServer) {
	// If the following call pancis, it indicates UnimplementedVoiceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VoiceService_ServiceDesc, srv)
}

func _VoiceService_ParseVoiceCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseVoiceCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).ParseVoiceCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_ParseVoiceCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).ParseVoiceCommand(ctx, req.(*ParseVoiceCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_MatchOfflinePhrase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchOfflinePhraseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).MatchOfflinePhrase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_MatchOfflinePhrase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).MatchOfflinePhrase(ctx, req.(*MatchOfflinePhraseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VoiceService_ServiceDesc is the grpc.ServiceDesc for VoiceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoiceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voice.v1.VoiceService",
	HandlerType: (*VoiceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseVoiceCommand",
			Handler:    _VoiceService_ParseVoiceCommand_Handler,
		},
		{
			MethodName: "MatchOfflinePhrase",
			Handler:    _VoiceService_MatchOfflinePhrase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "voice/v1/voice.proto",
}
