// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api_gateway/v1/gateway.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDashboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*DashboardRoom       `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	Incidents     []*DashboardIncident   `protobuf:"bytes,2,rep,name=incidents,proto3" json:"incidents,omitempty"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardResponse) Reset() {
	*x = GetDashboardResponse{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardResponse) ProtoMessage() {}

func (x *GetDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardResponse.ProtoReflect.Descriptor instead.
func (*GetDashboardResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GetDashboardResponse) GetRooms() []*DashboardRoom {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *GetDashboardResponse) GetIncidents() []*DashboardIncident {
	if x != nil {
		return x.Incidents
	}
	return nil
}

func (x *GetDashboardResponse) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

type DashboardRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardRoom) Reset() {
	*x = DashboardRoom{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardRoom) ProtoMessage() {}

func (x *DashboardRoom) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardRoom.ProtoReflect.Descriptor instead.
func (*DashboardRoom) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *DashboardRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *DashboardRoom) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DashboardRoom) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DashboardIncident struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncidentId    string                 `protobuf:"bytes,1,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardIncident) Reset() {
	*x = DashboardIncident{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardIncident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardIncident) ProtoMessage() {}

func (x *DashboardIncident) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardIncident.ProtoReflect.Descriptor instead.
func (*DashboardIncident) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *DashboardIncident) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *DashboardIncident) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DashboardIncident) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type ExecuteDeviceCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	TargetState   string                 `protobuf:"bytes,3,opt,name=target_state,json=targetState,proto3" json:"target_state,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteDeviceCommandRequest) Reset() {
	*x = ExecuteDeviceCommandRequest{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteDeviceCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteDeviceCommandRequest) ProtoMessage() {}

func (x *ExecuteDeviceCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteDeviceCommandRequest.ProtoReflect.Descriptor instead.
func (*ExecuteDeviceCommandRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteDeviceCommandRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ExecuteDeviceCommandRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ExecuteDeviceCommandRequest) GetTargetState() string {
	if x != nil {
		return x.TargetState
	}
	return ""
}

func (x *ExecuteDeviceCommandRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ExecuteDeviceCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteDeviceCommandResponse) Reset() {
	*x = ExecuteDeviceCommandResponse{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteDeviceCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteDeviceCommandResponse) ProtoMessage() {}

func (x *ExecuteDeviceCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteDeviceCommandResponse.ProtoReflect.Descriptor instead.
func (*ExecuteDeviceCommandResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteDeviceCommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ExecuteDeviceCommandResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SaveScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveScenarioRequest) Reset() {
	*x = SaveScenarioRequest{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveScenarioRequest) ProtoMessage() {}

func (x *SaveScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveScenarioRequest.ProtoReflect.Descriptor instead.
func (*SaveScenarioRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *SaveScenarioRequest) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *SaveScenarioRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveScenarioRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SaveScenarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveScenarioResponse) Reset() {
	*x = SaveScenarioResponse{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveScenarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveScenarioResponse) ProtoMessage() {}

func (x *SaveScenarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveScenarioResponse.ProtoReflect.Descriptor instead.
func (*SaveScenarioResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *SaveScenarioResponse) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *SaveScenarioResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ParseVoiceCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audio         []byte                 `protobuf:"bytes,1,opt,name=audio,proto3" json:"audio,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	EdgeId        string                 `protobuf:"bytes,3,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseVoiceCommandRequest) Reset() {
	*x = ParseVoiceCommandRequest{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseVoiceCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseVoiceCommandRequest) ProtoMessage() {}

func (x *ParseVoiceCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseVoiceCommandRequest.ProtoReflect.Descriptor instead.
func (*ParseVoiceCommandRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *ParseVoiceCommandRequest) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *ParseVoiceCommandRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ParseVoiceCommandRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

type ParseVoiceCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Intent        string                 `protobuf:"bytes,2,opt,name=intent,proto3" json:"intent,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseVoiceCommandResponse) Reset() {
	*x = ParseVoiceCommandResponse{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseVoiceCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseVoiceCommandResponse) ProtoMessage() {}

func (x *ParseVoiceCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseVoiceCommandResponse.ProtoReflect.Descriptor instead.
func (*ParseVoiceCommandResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *ParseVoiceCommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ParseVoiceCommandResponse) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *ParseVoiceCommandResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AnalyzeFrameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frame         []byte                 `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"`
	CameraId      string                 `protobuf:"bytes,2,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	EdgeId        string                 `protobuf:"bytes,3,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeFrameRequest) Reset() {
	*x = AnalyzeFrameRequest{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeFrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeFrameRequest) ProtoMessage() {}

func (x *AnalyzeFrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeFrameRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeFrameRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *AnalyzeFrameRequest) GetFrame() []byte {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *AnalyzeFrameRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *AnalyzeFrameRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

type AnalyzeFrameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeFrameResponse) Reset() {
	*x = AnalyzeFrameResponse{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeFrameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeFrameResponse) ProtoMessage() {}

func (x *AnalyzeFrameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeFrameResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeFrameResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *AnalyzeFrameResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AnalyzeFrameResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_api_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1capi_gateway/v1/gateway.proto\x12\x0eapi_gateway.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcb\x01\n" +
	"\x14GetDashboardResponse\x123\n" +
	"\x05rooms\x18\x01 \x03(\v2\x1d.api_gateway.v1.DashboardRoomR\x05rooms\x12?\n" +
	"\tincidents\x18\x02 \x03(\v2!.api_gateway.v1.DashboardIncidentR\tincidents\x12=\n" +
	"\fgenerated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\"T\n" +
	"\rDashboardRoom\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"d\n" +
	"\x11DashboardIncident\x12\x1f\n" +
	"\vincident_id\x18\x01 \x01(\tR\n" +
	"incidentId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\"\x92\x01\n" +
	"\x1bExecuteDeviceCommandRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12!\n" +
	"\ftarget_state\x18\x03 \x01(\tR\vtargetState\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"U\n" +
	"\x1cExecuteDeviceCommandResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"d\n" +
	"\x13SaveScenarioRequest\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\"O\n" +
	"\x14SaveScenarioResponse\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"b\n" +
	"\x18ParseVoiceCommandRequest\x12\x14\n" +
	"\x05audio\x18\x01 \x01(\fR\x05audio\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x17\n" +
	"\aedge_id\x18\x03 \x01(\tR\x06edgeId\"j\n" +
	"\x19ParseVoiceCommandResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06intent\x18\x02 \x01(\tR\x06intent\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"a\n" +
	"\x13AnalyzeFrameRequest\x12\x14\n" +
	"\x05frame\x18\x01 \x01(\fR\x05frame\x12\x1b\n" +
	"\tcamera_id\x18\x02 \x01(\tR\bcameraId\x12\x17\n" +
	"\aedge_id\x18\x03 \x01(\tR\x06edgeId\"M\n" +
	"\x14AnalyzeFrameResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xf1\x03\n" +
	"\x0eGatewayService\x12L\n" +
	"\fGetDashboard\x12\x16.google.protobuf.Empty\x1a$.api_gateway.v1.GetDashboardResponse\x12q\n" +
	"\x14ExecuteDeviceCommand\x12+.api_gateway.v1.ExecuteDeviceCommandRequest\x1a,.api_gateway.v1.ExecuteDeviceCommandResponse\x12Y\n" +
	"\fSaveScenario\x12#.api_gateway.v1.SaveScenarioRequest\x1a$.api_gateway.v1.SaveScenarioResponse\x12h\n" +
	"\x11ParseVoiceCommand\x12(.api_gateway.v1.ParseVoiceCommandRequest\x1a).api_gateway.v1.ParseVoiceCommandResponse\x12Y\n" +
	"\fAnalyzeFrame\x12#.api_gateway.v1.AnalyzeFrameRequest\x1a$.api_gateway.v1.AnalyzeFrameResponseB-Z+api-gateway/pkg/pb/api_gateway/v1;gatewayv1b\x06proto3"

var (
	file_api_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_api_gateway_v1_gateway_proto_rawDescData []byte
)

func file_api_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_api_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_api_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_v1_gateway_proto_rawDesc), len(file_api_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_api_gateway_v1_gateway_proto_rawDescData
}

var file_api_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_gateway_v1_gateway_proto_goTypes = []any{
	(*GetDashboardResponse)(nil),         // 0: api_gateway.v1.GetDashboardResponse
	(*DashboardRoom)(nil),                // 1: api_gateway.v1.DashboardRoom
	(*DashboardIncident)(nil),            // 2: api_gateway.v1.DashboardIncident
	(*ExecuteDeviceCommandRequest)(nil),  // 3: api_gateway.v1.ExecuteDeviceCommandRequest
	(*ExecuteDeviceCommandResponse)(nil), // 4: api_gateway.v1.ExecuteDeviceCommandResponse
	(*SaveScenarioRequest)(nil),          // 5: api_gateway.v1.SaveScenarioRequest
	(*SaveScenarioResponse)(nil),         // 6: api_gateway.v1.SaveScenarioResponse
	(*ParseVoiceCommandRequest)(nil),     // 7: api_gateway.v1.ParseVoiceCommandRequest
	(*ParseVoiceCommandResponse)(nil),    // 8: api_gateway.v1.ParseVoiceCommandResponse
	(*AnalyzeFrameRequest)(nil),          // 9: api_gateway.v1.AnalyzeFrameRequest
	(*AnalyzeFrameResponse)(nil),         // 10: api_gateway.v1.AnalyzeFrameResponse
	(*timestamppb.Timestamp)(nil),        // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 12: google.protobuf.Empty
}
var file_api_gateway_v1_gateway_proto_depIdxs = []int32{
	1,  // 0: api_gateway.v1.GetDashboardResponse.rooms:type_name -> api_gateway.v1.DashboardRoom
	2,  // 1: api_gateway.v1.GetDashboardResponse.incidents:type_name -> api_gateway.v1.DashboardIncident
	11, // 2: api_gateway.v1.GetDashboardResponse.generated_at:type_name -> google.protobuf.Timestamp
	12, // 3: api_gateway.v1.GatewayService.GetDashboard:input_type -> google.protobuf.Empty
	3,  // 4: api_gateway.v1.GatewayService.ExecuteDeviceCommand:input_type -> api_gateway.v1.ExecuteDeviceCommandRequest
	5,  // 5: api_gateway.v1.GatewayService.SaveScenario:input_type -> api_gateway.v1.SaveScenarioRequest
	7,  // 6: api_gateway.v1.GatewayService.ParseVoiceCommand:input_type -> api_gateway.v1.ParseVoiceCommandRequest
	9,  // 7: api_gateway.v1.GatewayService.AnalyzeFrame:input_type -> api_gateway.v1.AnalyzeFrameRequest
	0,  // 8: api_gateway.v1.GatewayService.GetDashboard:output_type -> api_gateway.v1.GetDashboardResponse
	4,  // 9: api_gateway.v1.GatewayService.ExecuteDeviceCommand:output_type -> api_gateway.v1.ExecuteDeviceCommandResponse
	6,  // 10: api_gateway.v1.GatewayService.SaveScenario:output_type -> api_gateway.v1.SaveScenarioResponse
	8,  // 11: api_gateway.v1.GatewayService.ParseVoiceCommand:output_type -> api_gateway.v1.ParseVoiceCommandResponse
	10, // 12: api_gateway.v1.GatewayService.AnalyzeFrame:output_type -> api_gateway.v1.AnalyzeFrameResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_gateway_v1_gateway_proto_init() }
func file_api_gateway_v1_gateway_proto_init() {
	if File_api_gateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_v1_gateway_proto_rawDesc), len(file_api_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_api_gateway_v1_gateway_proto_depIdxs,
		MessageInfos:      file_api_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_api_gateway_v1_gateway_proto = out.File
	file_api_gateway_v1_gateway_proto_goTypes = nil
	file_api_gateway_v1_gateway_proto_depIdxs = nil
}
