// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api_gateway/v1/gateway.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayService_GetDashboard_FullMethodName         = "/api_gateway.v1.GatewayService/GetDashboard"
	GatewayService_ExecuteDeviceCommand_FullMethodName = "/api_gateway.v1.GatewayService/ExecuteDeviceCommand"
	GatewayService_SaveScenario_FullMethodName         = "/api_gateway.v1.GatewayService/SaveScenario"
	GatewayService_ParseVoiceCommand_FullMethodName    = "/api_gateway.v1.GatewayService/ParseVoiceCommand"
	GatewayService_AnalyzeFrame_FullMethodName         = "/api_gateway.v1.GatewayService/AnalyzeFrame"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayServiceClient interface {
	GetDashboard(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetDashboardResponse, error)
	ExecuteDeviceCommand(ctx context.Context, in *ExecuteDeviceCommandRequest, opts ...grpc.CallOption) (*ExecuteDeviceCommandResponse, error)
	SaveScenario(ctx context.Context, in *SaveScenarioRequest, opts ...grpc.CallOption) (*SaveScenarioResponse, error)
	ParseVoiceCommand(ctx context.Context, in *ParseVoiceCommandRequest, opts ...grpc.CallOption) (*ParseVoiceCommandResponse, error)
	AnalyzeFrame(ctx context.Context, in *AnalyzeFrameRequest, opts ...grpc.CallOption) (*AnalyzeFrameResponse, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) GetDashboard(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetDashboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ExecuteDeviceCommand(ctx context.Context, in *ExecuteDeviceCommandRequest, opts ...grpc.CallOption) (*ExecuteDeviceCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteDeviceCommandResponse)
	err := c.cc.Invoke(ctx, GatewayService_ExecuteDeviceCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) SaveScenario(ctx context.Context, in *SaveScenarioRequest, opts ...grpc.CallOption) (*SaveScenarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveScenarioResponse)
	err := c.cc.Invoke(ctx, GatewayService_SaveScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ParseVoiceCommand(ctx context.Context, in *ParseVoiceCommandRequest, opts ...grpc.CallOption) (*ParseVoiceCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseVoiceCommandResponse)
	err := c.cc.Invoke(ctx, GatewayService_ParseVoiceCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) AnalyzeFrame(ctx context.Context, in *AnalyzeFrameRequest, opts ...grpc.CallOption) (*AnalyzeFrameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeFrameResponse)
	err := c.cc.Invoke(ctx, GatewayService_AnalyzeFrame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
type GatewayServiceServer interface {
	GetDashboard(context.Context, *emptypb.Empty) (*GetDashboardResponse, error)
	ExecuteDeviceCommand(context.Context, *ExecuteDeviceCommandRequest) (*ExecuteDeviceCommandResponse, error)
	SaveScenario(context.Context, *SaveScenarioRequest) (*SaveScenarioResponse, error)
	ParseVoiceCommand(context.Context, *ParseVoiceCommandRequest) (*ParseVoiceCommandResponse, error)
	AnalyzeFrame(context.Context, *AnalyzeFrameRequest) (*AnalyzeFrameResponse, error)
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) GetDashboard(context.Context, *emptypb.Empty) (*GetDashboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboard not implemented")
}
func (UnimplementedGatewayServiceServer) ExecuteDeviceCommand(context.Context, *ExecuteDeviceCommandRequest) (*ExecuteDeviceCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteDeviceCommand not implemented")
}
func (UnimplementedGatewayServiceServer) SaveScenario(context.Context, *SaveScenarioRequest) (*SaveScenarioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveScenario not implemented")
}
func (UnimplementedGatewayServiceServer) ParseVoiceCommand(context.Context, *ParseVoiceCommandRequest) (*ParseVoiceCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseVoiceCommand not implemented")
}
func (UnimplementedGatewayServiceServer) AnalyzeFrame(context.Context, *AnalyzeFrameRequest) (*AnalyzeFrameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeFrame not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call pancis, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_GetDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetDashboard(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ExecuteDeviceCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteDeviceCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ExecuteDeviceCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ExecuteDeviceCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ExecuteDeviceCommand(ctx, req.(*ExecuteDeviceCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_SaveScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).SaveScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_SaveScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).SaveScenario(ctx, req.(*SaveScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ParseVoiceCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseVoiceCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ParseVoiceCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ParseVoiceCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ParseVoiceCommand(ctx, req.(*ParseVoiceCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_AnalyzeFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeFrameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).AnalyzeFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_AnalyzeFrame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).AnalyzeFrame(ctx, req.(*AnalyzeFrameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api_gateway.v1.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDashboard",
			Handler:    _GatewayService_GetDashboard_Handler,
		},
		{
			MethodName: "ExecuteDeviceCommand",
			Handler:    _GatewayService_ExecuteDeviceCommand_Handler,
		},
		{
			MethodName: "SaveScenario",
			Handler:    _GatewayService_SaveScenario_Handler,
		},
		{
			MethodName: "ParseVoiceCommand",
			Handler:    _GatewayService_ParseVoiceCommand_Handler,
		},
		{
			MethodName: "AnalyzeFrame",
			Handler:    _GatewayService_AnalyzeFrame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api_gateway/v1/gateway.proto",
}
