// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: scenario/v1/scenario.proto

package scenariov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScenarioService_ListScenarios_FullMethodName       = "/scenario.v1.ScenarioService/ListScenarios"
	ScenarioService_GetScenario_FullMethodName         = "/scenario.v1.ScenarioService/GetScenario"
	ScenarioService_SaveScenario_FullMethodName        = "/scenario.v1.ScenarioService/SaveScenario"
	ScenarioService_EvaluateEvent_FullMethodName       = "/scenario.v1.ScenarioService/EvaluateEvent"
	ScenarioService_GetOfflineScenarios_FullMethodName = "/scenario.v1.ScenarioService/GetOfflineScenarios"
	ScenarioService_ListVoiceCommands_FullMethodName   = "/scenario.v1.ScenarioService/ListVoiceCommands"
	ScenarioService_ExecuteVoiceCommand_FullMethodName = "/scenario.v1.ScenarioService/ExecuteVoiceCommand"
)

// ScenarioServiceClient is the client API for ScenarioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScenarioServiceClient interface {
	ListScenarios(ctx context.Context, in *ListScenariosRequest, opts ...grpc.CallOption) (*ListScenariosResponse, error)
	GetScenario(ctx context.Context, in *GetScenarioRequest, opts ...grpc.CallOption) (*GetScenarioResponse, error)
	SaveScenario(ctx context.Context, in *SaveScenarioRequest, opts ...grpc.CallOption) (*SaveScenarioResponse, error)
	EvaluateEvent(ctx context.Context, in *EvaluateEventRequest, opts ...grpc.CallOption) (*EvaluateEventResponse, error)
	GetOfflineScenarios(ctx context.Context, in *GetOfflineScenariosRequest, opts ...grpc.CallOption) (*GetOfflineScenariosResponse, error)
	ListVoiceCommands(ctx context.Context, in *ListVoiceCommandsRequest, opts ...grpc.CallOption) (*ListVoiceCommandsResponse, error)
	ExecuteVoiceCommand(ctx context.Context, in *ExecuteVoiceCommandRequest, opts ...grpc.CallOption) (*ExecuteVoiceCommandResponse, error)
}

type scenarioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScenarioServiceClient(cc grpc.ClientConnInterface) ScenarioServiceClient {
	return &scenarioServiceClient{cc}
}

func (c *scenarioServiceClient) ListScenarios(ctx context.Context, in *ListScenariosRequest, opts ...grpc.CallOption) (*ListScenariosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScenariosResponse)
	err := c.cc.Invoke(ctx, ScenarioService_ListScenarios_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scenarioServiceClient) GetScenario(ctx context.Context, in *GetScenarioRequest, opts ...grpc.CallOption) (*GetScenarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScenarioResponse)
	err := c.cc.Invoke(ctx, ScenarioService_GetScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scenarioServiceClient) SaveScenario(ctx context.Context, in *SaveScenarioRequest, opts ...grpc.CallOption) (*SaveScenarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveScenarioResponse)
	err := c.cc.Invoke(ctx, ScenarioService_SaveScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scenarioServiceClient) EvaluateEvent(ctx context.Context, in *EvaluateEventRequest, opts ...grpc.CallOption) (*EvaluateEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateEventResponse)
	err := c.cc.Invoke(ctx, ScenarioService_EvaluateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scenarioServiceClient) GetOfflineScenarios(ctx context.Context, in *GetOfflineScenariosRequest, opts ...grpc.CallOption) (*GetOfflineScenariosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOfflineScenariosResponse)
	err := c.cc.Invoke(ctx, ScenarioService_GetOfflineScenarios_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scenarioServiceClient) ListVoiceCommands(ctx context.Context, in *ListVoiceCommandsRequest, opts ...grpc.CallOption) (*ListVoiceCommandsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVoiceCommandsResponse)
	err := c.cc.Invoke(ctx, ScenarioService_ListVoiceCommands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scenarioServiceClient) ExecuteVoiceCommand(ctx context.Context, in *ExecuteVoiceCommandRequest, opts ...grpc.CallOption) (*ExecuteVoiceCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteVoiceCommandResponse)
	err := c.cc.Invoke(ctx, ScenarioService_ExecuteVoiceCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScenarioServiceServer is the server API for ScenarioService service.
// All implementations must embed UnimplementedScenarioServiceServer
// for forward compatibility.
type ScenarioServiceServer interface {
	ListScenarios(context.Context, *ListScenariosRequest) (*ListScenariosResponse, error)
	GetScenario(context.Context, *GetScenarioRequest) (*GetScenarioResponse, error)
	SaveScenario(context.Context, *SaveScenarioRequest) (*SaveScenarioResponse, error)
	EvaluateEvent(context.Context, *EvaluateEventRequest) (*EvaluateEventResponse, error)
	GetOfflineScenarios(context.Context, *GetOfflineScenariosRequest) (*GetOfflineScenariosResponse, error)
	ListVoiceCommands(context.Context, *ListVoiceCommandsRequest) (*ListVoiceCommandsResponse, error)
	ExecuteVoiceCommand(context.Context, *ExecuteVoiceCommandRequest) (*ExecuteVoiceCommandResponse, error)
	mustEmbedUnimplementedScenarioServiceServer()
}

// UnimplementedScenarioServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScenarioServiceServer struct{}

func (UnimplementedScenarioServiceServer) ListScenarios(context.Context, *ListScenariosRequest) (*ListScenariosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListScenarios not implemented")
}
func (UnimplementedScenarioServiceServer) GetScenario(context.Context, *GetScenarioRequest) (*GetScenarioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScenario not implemented")
}
func (UnimplementedScenarioServiceServer) SaveScenario(context.Context, *SaveScenarioRequest) (*SaveScenarioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveScenario not implemented")
}
func (UnimplementedScenarioServiceServer) EvaluateEvent(context.Context, *EvaluateEventRequest) (*EvaluateEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateEvent not implemented")
}
func (UnimplementedScenarioServiceServer) GetOfflineScenarios(context.Context, *GetOfflineScenariosRequest) (*GetOfflineScenariosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOfflineScenarios not implemented")
}
func (UnimplementedScenarioServiceServer) ListVoiceCommands(context.Context, *ListVoiceCommandsRequest) (*ListVoiceCommandsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVoiceCommands not implemented")
}
func (UnimplementedScenarioServiceServer) ExecuteVoiceCommand(context.Context, *ExecuteVoiceCommandRequest) (*ExecuteVoiceCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteVoiceCommand not implemented")
}
func (UnimplementedScenarioServiceServer) mustEmbedUnimplementedScenarioServiceServer() {}
func (UnimplementedScenarioServiceServer) testEmbeddedByValue()                         {}

// UnsafeScenarioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScenarioServiceServer will
// result in compilation errors.
type UnsafeScenarioServiceServer interface {
	mustEmbedUnimplementedScenarioServiceServer()
}

func RegisterScenarioServiceServer(s grpc.ServiceRegistrar, srv ScenarioServiceServer) {
	// If the following call pancis, it indicates UnimplementedScenarioServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScenarioService_ServiceDesc, srv)
}

func _ScenarioService_ListScenarios_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScenariosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenarioServiceServer).ListScenarios(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScenarioService_ListScenarios_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenarioServiceServer).ListScenarios(ctx, req.(*ListScenariosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScenarioService_GetScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenarioServiceServer).GetScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScenarioService_GetScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenarioServiceServer).GetScenario(ctx, req.(*GetScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScenarioService_SaveScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenarioServiceServer).SaveScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScenarioService_SaveScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenarioServiceServer).SaveScenario(ctx, req.(*SaveScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScenarioService_EvaluateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenarioServiceServer).EvaluateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScenarioService_EvaluateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenarioServiceServer).EvaluateEvent(ctx, req.(*EvaluateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScenarioService_GetOfflineScenarios_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOfflineScenariosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenarioServiceServer).GetOfflineScenarios(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScenarioService_GetOfflineScenarios_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenarioServiceServer).GetOfflineScenarios(ctx, req.(*GetOfflineScenariosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScenarioService_ListVoiceCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVoiceCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenarioServiceServer).ListVoiceCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScenarioService_ListVoiceCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenarioServiceServer).ListVoiceCommands(ctx, req.(*ListVoiceCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScenarioService_ExecuteVoiceCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteVoiceCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenarioServiceServer).ExecuteVoiceCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScenarioService_ExecuteVoiceCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenarioServiceServer).ExecuteVoiceCommand(ctx, req.(*ExecuteVoiceCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScenarioService_ServiceDesc is the grpc.ServiceDesc for ScenarioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScenarioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scenario.v1.ScenarioService",
	HandlerType: (*ScenarioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListScenarios",
			Handler:    _ScenarioService_ListScenarios_Handler,
		},
		{
			MethodName: "GetScenario",
			Handler:    _ScenarioService_GetScenario_Handler,
		},
		{
			MethodName: "SaveScenario",
			Handler:    _ScenarioService_SaveScenario_Handler,
		},
		{
			MethodName: "EvaluateEvent",
			Handler:    _ScenarioService_EvaluateEvent_Handler,
		},
		{
			MethodName: "GetOfflineScenarios",
			Handler:    _ScenarioService_GetOfflineScenarios_Handler,
		},
		{
			MethodName: "ListVoiceCommands",
			Handler:    _ScenarioService_ListVoiceCommands_Handler,
		},
		{
			MethodName: "ExecuteVoiceCommand",
			Handler:    _ScenarioService_ExecuteVoiceCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scenario/v1/scenario.proto",
}
