// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: scenario/v1/scenario.proto

package scenariov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TriggerType   string                 `protobuf:"bytes,1,opt,name=trigger_type,json=triggerType,proto3" json:"trigger_type,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EntityId      string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	ExpectedState string                 `protobuf:"bytes,4,opt,name=expected_state,json=expectedState,proto3" json:"expected_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trigger) Reset() {
	*x = Trigger{}
	mi := &file_scenario_v1_scenario_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trigger) ProtoMessage() {}

func (x *Trigger) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_v1_scenario_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trigger.ProtoReflect.Descriptor instead.
func (*Trigger) Descriptor() ([]byte, []int) {
	return file_scenario_v1_scenario_proto_rawDescGZIP(), []int{0}
}

func (x *Trigger) GetTriggerType() string {
	if x != nil {
		return x.TriggerType
	}
	return ""
}

func (x *Trigger) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Trigger) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Trigger) GetExpectedState() string {
	if x != nil {
		return x.ExpectedState
	}
	return ""
}

type Condition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConditionType string                 `protobuf:"bytes,1,opt,name=condition_type,json=conditionType,proto3" json:"condition_type,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	ExpectedValue string                 `protobuf:"bytes,3,opt,name=expected_value,json=expectedValue,proto3" json:"expected_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_scenario_v1_scenario_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_v1_scenario_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_scenario_v1_scenario_proto_rawDescGZIP(), []int{1}
}

func (x *Condition) GetConditionType() string {
	if x != nil {
		return x.ConditionType
	}
	return ""
}

func (x *Condition) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Condition) GetExpectedValue() string {
	if x != nil {
		return x.ExpectedValue
	}
	return ""
}

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionType    string                 `protobuf:"bytes,1,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	EntityId      string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	TargetState   string                 `protobuf:"bytes,4,opt,name=target_state,json=targetState,proto3" json:"target_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_scenario_v1_scenario_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_v1_scenario_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_scenario_v1_scenario_proto_rawDescGZIP(), []int{2}
}

func (x *Action) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *Action) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Action) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Action) GetTargetState() string {
	if x != nil {
		return x.TargetState
	}
	return ""
}

type Scenario struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId      string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	EdgeId          string                 `protobuf:"bytes,2,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Enabled         bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Priority        int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	OfflineEligible bool                   `protobuf:"varint,6,opt,name=offline_eligible,json=offlineEligible,proto3" json:"offline_eligible,omitempty"`
	Triggers        []*Trigger             `protobuf:"bytes,7,rep,name=triggers,proto3" json:"triggers,omitempty"`
	Conditions      []*Condition           `protobuf:"bytes,8,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Actions         []*Action              `protobuf:"bytes,9,rep,name=actions,proto3" json:"actions,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Scenario) Reset() {
	*x = Scenario{}
	mi := &file_scenario_v1_scenario_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scenario) ProtoMessage() {}

func (x *Scenario) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_v1_scenario_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scenario.ProtoReflect.Descriptor instead.
func (*Scenario) Descriptor() ([]byte, []int) {
	return file_scenario_v1_scenario_proto_rawDescGZIP(), []int{3}
}

func (x *Scenario) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *Scenario) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *Scenario) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Scenario) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Scenario) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Scenario) GetOfflineEligible() bool {
	if x != nil {
		return x.OfflineEligible
	}
	return false
}

func (x *Scenario) GetTriggers() []*Trigger {
	if x != nil {
		return x.Triggers
	}
	return nil
}

func (x *Scenario) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *Scenario) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *Scenario) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type EventEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EdgeId        string                 `protobuf:"bytes,2,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	EntityId      string                 `protobuf:"bytes,4,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EventType     string                 `protobuf:"bytes,5,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	State         string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_scenario_v1_scenario_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_v1_scenario_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_scenario_v1_scenario_proto_rawDescGZIP(), []int{4}
}

func (x *EventEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventEnvelope) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *EventEnvelope) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *EventEnvelope) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *EventEnvelope) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventEnvelope) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *EventEnvelope) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

type Decision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DecisionId    string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Actions       []*Action              `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_scenario_v1_scenario_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_v1_scenario_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_scenario_v1_scenario_proto_rawDescGZIP(), []int{5}
}

func (x *Decision) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *Decision) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Decision) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type ListScenariosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScenariosRequest) Reset() {
	*x = ListScenariosRequest{}
	mi := &file_scenario_v1_scenario_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScenariosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenariosRequest) ProtoMessage() {}

func (x *ListScenariosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_v1_scenario_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenariosRequest.ProtoReflect.Descriptor instead.
func (*ListScenariosRequest) Descriptor() ([]byte, []int) {
	return file_scenario_v1_scenario_proto_rawDescGZIP(), []int{6}
}

func (x *ListScenariosRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

type ListScenariosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenarios     []*Scenario            `protobuf:"bytes,1,rep,name=scenarios,proto3" json:"scenarios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScenariosResponse) Reset() {
	*x = ListScenariosResponse{}
	mi := &file_scenario_v1_scenario_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScenariosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenariosResponse) ProtoMessage() {}

func (x *ListScenariosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_v1_scenario_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenariosResponse.ProtoReflect.Descriptor instead.
func (*ListScenariosResponse) Descriptor() ([]byte, []int) {
	return file_scenario_v1_scenario_proto_rawDescGZIP(), []int{7}
}

func (x *ListScenariosResponse) GetScenarios() []*Scenario {
	if x != nil {
		return x.Scenarios
	}
	return nil
}

type GetScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScenarioRequest) Reset() {
	*x = GetScenarioRequest{}
	mi := &file_scenario_v1_scenario_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScenarioRequest) ProtoMessage() {}

func (x *GetScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_v1_scenario_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScenarioRequest.ProtoReflect.Descriptor instead.
func (*GetScenarioRequest) Descriptor() ([]byte, []int) {
	return file_scenario_v1_scenario_proto_rawDescGZIP(), []int{8}
}

func (x *GetScenarioRequest) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

type GetScenarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenario      *Scenario              `protobuf:"bytes,1,opt,name=scenario,proto3" json:"scenario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScenarioResponse) Reset() {
	*x = GetScenarioResponse{}
	mi := &file_scenario_v1_scenario_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScenarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScenarioResponse) ProtoMessage() {}

func (x *GetScenarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_v1_scenario_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScenarioResponse.ProtoReflect.Descriptor instead.
func (*GetScenarioResponse) Descriptor() ([]byte, []int) {
	return file_scenario_v1_scenario_proto_rawDescGZIP(), []int{9}
}

func (x *GetScenarioResponse) GetScenario() *Scenario {
	if x != nil {
		return x.Scenario
	}
	return nil
}

type SaveScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenario      *Scenario              `protobuf:"bytes,1,opt,name=scenario,proto3" json:"scenario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveScenarioRequest) Reset() {
	*x = SaveScenarioRequest{}
	mi := &file_scenario_v1_scenario_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveScenarioRequest) ProtoMessage() {}

func (x *SaveScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_v1_scenario_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveScenarioRequest.ProtoReflect.Descriptor instead.
func (*SaveScenarioRequest) Descriptor() ([]byte, []int) {
	return file_scenario_v1_scenario_proto_rawDescGZIP(), []int{10}
}

func (x *SaveScenarioRequest) GetScenario() *Scenario {
	if x != nil {
		return x.Scenario
	}
	return nil
}

type SaveScenarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenario      *Scenario              `protobuf:"bytes,1,opt,name=scenario,proto3" json:"scenario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveScenarioResponse) Reset() {
	*x = SaveScenarioResponse{}
	mi := &file_scenario_v1_scenario_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveScenarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveScenarioResponse) ProtoMessage() {}

func (x *SaveScenarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_v1_scenario_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveScenarioResponse.ProtoReflect.Descriptor instead.
func (*SaveScenarioResponse) Descriptor() ([]byte, []int) {
	return file_scenario_v1_scenario_proto_rawDescGZIP(), []int{11}
}

func (x *SaveScenarioResponse) GetScenario() *Scenario {
	if x != nil {
		return x.Scenario
	}
	return nil
}

type EvaluateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *EventEnvelope         `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateEventRequest) Reset() {
	*x = EvaluateEventRequest{}
	mi := &file_scenario_v1_scenario_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateEventRequest) ProtoMessage() {}

func (x *EvaluateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_v1_scenario_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateEventRequest.ProtoReflect.Descriptor instead.
func (*EvaluateEventRequest) Descriptor() ([]byte, []int) {
	return file_scenario_v1_scenario_proto_rawDescGZIP(), []int{12}
}

func (x *EvaluateEventRequest) GetEvent() *EventEnvelope {
	if x != nil {
		return x.Event
	}
	return nil
}

type EvaluateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      *Decision              `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateEventResponse) Reset() {
	*x = EvaluateEventResponse{}
	mi := &file_scenario_v1_scenario_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateEventResponse) ProtoMessage() {}

func (x *EvaluateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_v1_scenario_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateEventResponse.ProtoReflect.Descriptor instead.
func (*EvaluateEventResponse) Descriptor() ([]byte, []int) {
	return file_scenario_v1_scenario_proto_rawDescGZIP(), []int{13}
}

func (x *EvaluateEventResponse) GetDecision() *Decision {
	if x != nil {
		return x.Decision
	}
	return nil
}

type GetOfflineScenariosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOfflineScenariosRequest) Reset() {
	*x = GetOfflineScenariosRequest{}
	mi := &file_scenario_v1_scenario_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOfflineScenariosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfflineScenariosRequest) ProtoMessage() {}

func (x *GetOfflineScenariosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_v1_scenario_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfflineScenariosRequest.ProtoReflect.Descriptor instead.
func (*GetOfflineScenariosRequest) Descriptor() ([]byte, []int) {
	return file_scenario_v1_scenario_proto_rawDescGZIP(), []int{14}
}

func (x *GetOfflineScenariosRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

type GetOfflineScenariosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenarios     []*Scenario            `protobuf:"bytes,1,rep,name=scenarios,proto3" json:"scenarios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOfflineScenariosResponse) Reset() {
	*x = GetOfflineScenariosResponse{}
	mi := &file_scenario_v1_scenario_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOfflineScenariosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfflineScenariosResponse) ProtoMessage() {}

func (x *GetOfflineScenariosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_v1_scenario_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfflineScenariosResponse.ProtoReflect.Descriptor instead.
func (*GetOfflineScenariosResponse) Descriptor() ([]byte, []int) {
	return file_scenario_v1_scenario_proto_rawDescGZIP(), []int{15}
}

func (x *GetOfflineScenariosResponse) GetScenarios() []*Scenario {
	if x != nil {
		return x.Scenarios
	}
	return nil
}

var File_scenario_v1_scenario_proto protoreflect.FileDescriptor

const file_scenario_v1_scenario_proto_rawDesc = "" +
	"\n" +
	"\x1ascenario/v1/scenario.proto\x12\vscenario.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\x01\n" +
	"\aTrigger\x12!\n" +
	"\ftrigger_type\x18\x01 \x01(\tR\vtriggerType\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12%\n" +
	"\x0eexpected_state\x18\x04 \x01(\tR\rexpectedState\"o\n" +
	"\tCondition\x12%\n" +
	"\x0econdition_type\x18\x01 \x01(\tR\rconditionType\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12%\n" +
	"\x0eexpected_value\x18\x03 \x01(\tR\rexpectedValue\"\x86\x01\n" +
	"\x06Action\x12\x1f\n" +
	"\vaction_type\x18\x01 \x01(\tR\n" +
	"actionType\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12!\n" +
	"\ftarget_state\x18\x04 \x01(\tR\vtargetState\"\x8d\x03\n" +
	"\bScenario\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x17\n" +
	"\aedge_id\x18\x02 \x01(\tR\x06edgeId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12)\n" +
	"\x10offline_eligible\x18\x06 \x01(\bR\x0fofflineEligible\x120\n" +
	"\btriggers\x18\a \x03(\v2\x14.scenario.v1.TriggerR\btriggers\x126\n" +
	"\n" +
	"conditions\x18\b \x03(\v2\x16.scenario.v1.ConditionR\n" +
	"conditions\x12-\n" +
	"\aactions\x18\t \x03(\v2\x13.scenario.v1.ActionR\aactions\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xeb\x01\n" +
	"\rEventEnvelope\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\aedge_id\x18\x02 \x01(\tR\x06edgeId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tentity_id\x18\x04 \x01(\tR\bentityId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x05 \x01(\tR\teventType\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12;\n" +
	"\voccurred_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"r\n" +
	"\bDecision\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12-\n" +
	"\aactions\x18\x03 \x03(\v2\x13.scenario.v1.ActionR\aactions\"/\n" +
	"\x14ListScenariosRequest\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\"L\n" +
	"\x15ListScenariosResponse\x123\n" +
	"\tscenarios\x18\x01 \x03(\v2\x15.scenario.v1.ScenarioR\tscenarios\"5\n" +
	"\x12GetScenarioRequest\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\"H\n" +
	"\x13GetScenarioResponse\x121\n" +
	"\bscenario\x18\x01 \x01(\v2\x15.scenario.v1.ScenarioR\bscenario\"H\n" +
	"\x13SaveScenarioRequest\x121\n" +
	"\bscenario\x18\x01 \x01(\v2\x15.scenario.v1.ScenarioR\bscenario\"I\n" +
	"\x14SaveScenarioResponse\x121\n" +
	"\bscenario\x18\x01 \x01(\v2\x15.scenario.v1.ScenarioR\bscenario\"H\n" +
	"\x14EvaluateEventRequest\x120\n" +
	"\x05event\x18\x01 \x01(\v2\x1a.scenario.v1.EventEnvelopeR\x05event\"J\n" +
	"\x15EvaluateEventResponse\x121\n" +
	"\bdecision\x18\x01 \x01(\v2\x15.scenario.v1.DecisionR\bdecision\"5\n" +
	"\x1aGetOfflineScenariosRequest\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\"R\n" +
	"\x1bGetOfflineScenariosResponse\x123\n" +
	"\tscenarios\x18\x01 \x03(\v2\x15.scenario.v1.ScenarioR\tscenarios2\xd2\x03\n" +
	"\x0fScenarioService\x12V\n" +
	"\rListScenarios\x12!.scenario.v1.ListScenariosRequest\x1a\".scenario.v1.ListScenariosResponse\x12P\n" +
	"\vGetScenario\x12\x1f.scenario.v1.GetScenarioRequest\x1a .scenario.v1.GetScenarioResponse\x12S\n" +
	"\fSaveScenario\x12 .scenario.v1.SaveScenarioRequest\x1a!.scenario.v1.SaveScenarioResponse\x12V\n" +
	"\rEvaluateEvent\x12!.scenario.v1.EvaluateEventRequest\x1a\".scenario.v1.EvaluateEventResponse\x12h\n" +
	"\x13GetOfflineScenarios\x12'.scenario.v1.GetOfflineScenariosRequest\x1a(.scenario.v1.GetOfflineScenariosResponseB0Z.scenario-service/pkg/pb/scenario/v1;scenariov1b\x06proto3"

var (
	file_scenario_v1_scenario_proto_rawDescOnce sync.Once
	file_scenario_v1_scenario_proto_rawDescData []byte
)

func file_scenario_v1_scenario_proto_rawDescGZIP() []byte {
	file_scenario_v1_scenario_proto_rawDescOnce.Do(func() {
		file_scenario_v1_scenario_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scenario_v1_scenario_proto_rawDesc), len(file_scenario_v1_scenario_proto_rawDesc)))
	})
	return file_scenario_v1_scenario_proto_rawDescData
}

var file_scenario_v1_scenario_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_scenario_v1_scenario_proto_goTypes = []any{
	(*Trigger)(nil),                     // 0: scenario.v1.Trigger
	(*Condition)(nil),                   // 1: scenario.v1.Condition
	(*Action)(nil),                      // 2: scenario.v1.Action
	(*Scenario)(nil),                    // 3: scenario.v1.Scenario
	(*EventEnvelope)(nil),               // 4: scenario.v1.EventEnvelope
	(*Decision)(nil),                    // 5: scenario.v1.Decision
	(*ListScenariosRequest)(nil),        // 6: scenario.v1.ListScenariosRequest
	(*ListScenariosResponse)(nil),       // 7: scenario.v1.ListScenariosResponse
	(*GetScenarioRequest)(nil),          // 8: scenario.v1.GetScenarioRequest
	(*GetScenarioResponse)(nil),         // 9: scenario.v1.GetScenarioResponse
	(*SaveScenarioRequest)(nil),         // 10: scenario.v1.SaveScenarioRequest
	(*SaveScenarioResponse)(nil),        // 11: scenario.v1.SaveScenarioResponse
	(*EvaluateEventRequest)(nil),        // 12: scenario.v1.EvaluateEventRequest
	(*EvaluateEventResponse)(nil),       // 13: scenario.v1.EvaluateEventResponse
	(*GetOfflineScenariosRequest)(nil),  // 14: scenario.v1.GetOfflineScenariosRequest
	(*GetOfflineScenariosResponse)(nil), // 15: scenario.v1.GetOfflineScenariosResponse
	(*timestamppb.Timestamp)(nil),       // 16: google.protobuf.Timestamp
}
var file_scenario_v1_scenario_proto_depIdxs = []int32{
	0,  // 0: scenario.v1.Scenario.triggers:type_name -> scenario.v1.Trigger
	1,  // 1: scenario.v1.Scenario.conditions:type_name -> scenario.v1.Condition
	2,  // 2: scenario.v1.Scenario.actions:type_name -> scenario.v1.Action
	16, // 3: scenario.v1.Scenario.updated_at:type_name -> google.protobuf.Timestamp
	16, // 4: scenario.v1.EventEnvelope.occurred_at:type_name -> google.protobuf.Timestamp
	2,  // 5: scenario.v1.Decision.actions:type_name -> scenario.v1.Action
	3,  // 6: scenario.v1.ListScenariosResponse.scenarios:type_name -> scenario.v1.Scenario
	3,  // 7: scenario.v1.GetScenarioResponse.scenario:type_name -> scenario.v1.Scenario
	3,  // 8: scenario.v1.SaveScenarioRequest.scenario:type_name -> scenario.v1.Scenario
	3,  // 9: scenario.v1.SaveScenarioResponse.scenario:type_name -> scenario.v1.Scenario
	4,  // 10: scenario.v1.EvaluateEventRequest.event:type_name -> scenario.v1.EventEnvelope
	5,  // 11: scenario.v1.EvaluateEventResponse.decision:type_name -> scenario.v1.Decision
	3,  // 12: scenario.v1.GetOfflineScenariosResponse.scenarios:type_name -> scenario.v1.Scenario
	6,  // 13: scenario.v1.ScenarioService.ListScenarios:input_type -> scenario.v1.ListScenariosRequest
	8,  // 14: scenario.v1.ScenarioService.GetScenario:input_type -> scenario.v1.GetScenarioRequest
	10, // 15: scenario.v1.ScenarioService.SaveScenario:input_type -> scenario.v1.SaveScenarioRequest
	12, // 16: scenario.v1.ScenarioService.EvaluateEvent:input_type -> scenario.v1.EvaluateEventRequest
	14, // 17: scenario.v1.ScenarioService.GetOfflineScenarios:input_type -> scenario.v1.GetOfflineScenariosRequest
	7,  // 18: scenario.v1.ScenarioService.ListScenarios:output_type -> scenario.v1.ListScenariosResponse
	9,  // 19: scenario.v1.ScenarioService.GetScenario:output_type -> scenario.v1.GetScenarioResponse
	11, // 20: scenario.v1.ScenarioService.SaveScenario:output_type -> scenario.v1.SaveScenarioResponse
	13, // 21: scenario.v1.ScenarioService.EvaluateEvent:output_type -> scenario.v1.EvaluateEventResponse
	15, // 22: scenario.v1.ScenarioService.GetOfflineScenarios:output_type -> scenario.v1.GetOfflineScenariosResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_scenario_v1_scenario_proto_init() }
func file_scenario_v1_scenario_proto_init() {
	if File_scenario_v1_scenario_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scenario_v1_scenario_proto_rawDesc), len(file_scenario_v1_scenario_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scenario_v1_scenario_proto_goTypes,
		DependencyIndexes: file_scenario_v1_scenario_proto_depIdxs,
		MessageInfos:      file_scenario_v1_scenario_proto_msgTypes,
	}.Build()
	File_scenario_v1_scenario_proto = out.File
	file_scenario_v1_scenario_proto_goTypes = nil
	file_scenario_v1_scenario_proto_depIdxs = nil
}
