// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: context/v1/context.proto

package contextv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvironmentSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignalId      string                 `protobuf:"bytes,1,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	SignalType    string                 `protobuf:"bytes,4,opt,name=signal_type,json=signalType,proto3" json:"signal_type,omitempty"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentSignal) Reset() {
	*x = EnvironmentSignal{}
	mi := &file_context_v1_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentSignal) ProtoMessage() {}

func (x *EnvironmentSignal) ProtoReflect() protoreflect.Message {
	mi := &file_context_v1_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentSignal.ProtoReflect.Descriptor instead.
func (*EnvironmentSignal) Descriptor() ([]byte, []int) {
	return file_context_v1_context_proto_rawDescGZIP(), []int{0}
}

func (x *EnvironmentSignal) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

func (x *EnvironmentSignal) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EnvironmentSignal) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *EnvironmentSignal) GetSignalType() string {
	if x != nil {
		return x.SignalType
	}
	return ""
}

func (x *EnvironmentSignal) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EnvironmentSignal) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

type HomeContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Mode           string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	OccupancyState string                 `protobuf:"bytes,2,opt,name=occupancy_state,json=occupancyState,proto3" json:"occupancy_state,omitempty"`
	ComfortState   string                 `protobuf:"bytes,3,opt,name=comfort_state,json=comfortState,proto3" json:"comfort_state,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HomeContext) Reset() {
	*x = HomeContext{}
	mi := &file_context_v1_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeContext) ProtoMessage() {}

func (x *HomeContext) ProtoReflect() protoreflect.Message {
	mi := &file_context_v1_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeContext.ProtoReflect.Descriptor instead.
func (*HomeContext) Descriptor() ([]byte, []int) {
	return file_context_v1_context_proto_rawDescGZIP(), []int{1}
}

func (x *HomeContext) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *HomeContext) GetOccupancyState() string {
	if x != nil {
		return x.OccupancyState
	}
	return ""
}

func (x *HomeContext) GetComfortState() string {
	if x != nil {
		return x.ComfortState
	}
	return ""
}

func (x *HomeContext) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RoomContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomId         string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	OccupancyState string                 `protobuf:"bytes,2,opt,name=occupancy_state,json=occupancyState,proto3" json:"occupancy_state,omitempty"`
	ClimateState   string                 `protobuf:"bytes,3,opt,name=climate_state,json=climateState,proto3" json:"climate_state,omitempty"`
	LightState     string                 `protobuf:"bytes,4,opt,name=light_state,json=lightState,proto3" json:"light_state,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RoomContext) Reset() {
	*x = RoomContext{}
	mi := &file_context_v1_context_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomContext) ProtoMessage() {}

func (x *RoomContext) ProtoReflect() protoreflect.Message {
	mi := &file_context_v1_context_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomContext.ProtoReflect.Descriptor instead.
func (*RoomContext) Descriptor() ([]byte, []int) {
	return file_context_v1_context_proto_rawDescGZIP(), []int{2}
}

func (x *RoomContext) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomContext) GetOccupancyState() string {
	if x != nil {
		return x.OccupancyState
	}
	return ""
}

func (x *RoomContext) GetClimateState() string {
	if x != nil {
		return x.ClimateState
	}
	return ""
}

func (x *RoomContext) GetLightState() string {
	if x != nil {
		return x.LightState
	}
	return ""
}

func (x *RoomContext) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PresenceContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectId     string                 `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Confidence    float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceContext) Reset() {
	*x = PresenceContext{}
	mi := &file_context_v1_context_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceContext) ProtoMessage() {}

func (x *PresenceContext) ProtoReflect() protoreflect.Message {
	mi := &file_context_v1_context_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceContext.ProtoReflect.Descriptor instead.
func (*PresenceContext) Descriptor() ([]byte, []int) {
	return file_context_v1_context_proto_rawDescGZIP(), []int{3}
}

func (x *PresenceContext) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *PresenceContext) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PresenceContext) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PresenceContext) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PresenceContext) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *PresenceContext) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetHomeContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHomeContextRequest) Reset() {
	*x = GetHomeContextRequest{}
	mi := &file_context_v1_context_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHomeContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHomeContextRequest) ProtoMessage() {}

func (x *GetHomeContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_context_v1_context_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHomeContextRequest.ProtoReflect.Descriptor instead.
func (*GetHomeContextRequest) Descriptor() ([]byte, []int) {
	return file_context_v1_context_proto_rawDescGZIP(), []int{4}
}

type GetHomeContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *HomeContext           `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHomeContextResponse) Reset() {
	*x = GetHomeContextResponse{}
	mi := &file_context_v1_context_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHomeContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHomeContextResponse) ProtoMessage() {}

func (x *GetHomeContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_context_v1_context_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHomeContextResponse.ProtoReflect.Descriptor instead.
func (*GetHomeContextResponse) Descriptor() ([]byte, []int) {
	return file_context_v1_context_proto_rawDescGZIP(), []int{5}
}

func (x *GetHomeContextResponse) GetContext() *HomeContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type GetRoomContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomContextRequest) Reset() {
	*x = GetRoomContextRequest{}
	mi := &file_context_v1_context_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomContextRequest) ProtoMessage() {}

func (x *GetRoomContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_context_v1_context_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomContextRequest.ProtoReflect.Descriptor instead.
func (*GetRoomContextRequest) Descriptor() ([]byte, []int) {
	return file_context_v1_context_proto_rawDescGZIP(), []int{6}
}

func (x *GetRoomContextRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GetRoomContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RoomContext           `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomContextResponse) Reset() {
	*x = GetRoomContextResponse{}
	mi := &file_context_v1_context_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomContextResponse) ProtoMessage() {}

func (x *GetRoomContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_context_v1_context_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomContextResponse.ProtoReflect.Descriptor instead.
func (*GetRoomContextResponse) Descriptor() ([]byte, []int) {
	return file_context_v1_context_proto_rawDescGZIP(), []int{7}
}

func (x *GetRoomContextResponse) GetContext() *RoomContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type IngestSignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signal        *EnvironmentSignal     `protobuf:"bytes,1,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestSignalRequest) Reset() {
	*x = IngestSignalRequest{}
	mi := &file_context_v1_context_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestSignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSignalRequest) ProtoMessage() {}

func (x *IngestSignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_context_v1_context_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSignalRequest.ProtoReflect.Descriptor instead.
func (*IngestSignalRequest) Descriptor() ([]byte, []int) {
	return file_context_v1_context_proto_rawDescGZIP(), []int{8}
}

func (x *IngestSignalRequest) GetSignal() *EnvironmentSignal {
	if x != nil {
		return x.Signal
	}
	return nil
}

type IngestSignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestSignalResponse) Reset() {
	*x = IngestSignalResponse{}
	mi := &file_context_v1_context_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestSignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSignalResponse) ProtoMessage() {}

func (x *IngestSignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_context_v1_context_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSignalResponse.ProtoReflect.Descriptor instead.
func (*IngestSignalResponse) Descriptor() ([]byte, []int) {
	return file_context_v1_context_proto_rawDescGZIP(), []int{9}
}

func (x *IngestSignalResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetPresenceContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectId     string                 `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceContextRequest) Reset() {
	*x = GetPresenceContextRequest{}
	mi := &file_context_v1_context_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceContextRequest) ProtoMessage() {}

func (x *GetPresenceContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_context_v1_context_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceContextRequest.ProtoReflect.Descriptor instead.
func (*GetPresenceContextRequest) Descriptor() ([]byte, []int) {
	return file_context_v1_context_proto_rawDescGZIP(), []int{10}
}

func (x *GetPresenceContextRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

type GetPresenceContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *PresenceContext       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceContextResponse) Reset() {
	*x = GetPresenceContextResponse{}
	mi := &file_context_v1_context_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceContextResponse) ProtoMessage() {}

func (x *GetPresenceContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_context_v1_context_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceContextResponse.ProtoReflect.Descriptor instead.
func (*GetPresenceContextResponse) Descriptor() ([]byte, []int) {
	return file_context_v1_context_proto_rawDescGZIP(), []int{11}
}

func (x *GetPresenceContextResponse) GetContext() *PresenceContext {
	if x != nil {
		return x.Context
	}
	return nil
}

var File_context_v1_context_proto protoreflect.FileDescriptor

const file_context_v1_context_proto_rawDesc = "" +
	"\n" +
	"\x18context/v1/context.proto\x12\n" +
	"context.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd5\x01\n" +
	"\x11EnvironmentSignal\x12\x1b\n" +
	"\tsignal_id\x18\x01 \x01(\tR\bsignalId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vsignal_type\x18\x04 \x01(\tR\n" +
	"signalType\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\x12;\n" +
	"\vobserved_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\"\xaa\x01\n" +
	"\vHomeContext\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12'\n" +
	"\x0foccupancy_state\x18\x02 \x01(\tR\x0eoccupancyState\x12#\n" +
	"\rcomfort_state\x18\x03 \x01(\tR\fcomfortState\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd0\x01\n" +
	"\vRoomContext\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12'\n" +
	"\x0foccupancy_state\x18\x02 \x01(\tR\x0eoccupancyState\x12#\n" +
	"\rclimate_state\x18\x03 \x01(\tR\fclimateState\x12\x1f\n" +
	"\vlight_state\x18\x04 \x01(\tR\n" +
	"lightState\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd4\x01\n" +
	"\x0fPresenceContext\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x17\n" +
	"\x15GetHomeContextRequest\"K\n" +
	"\x16GetHomeContextResponse\x121\n" +
	"\acontext\x18\x01 \x01(\v2\x17.context.v1.HomeContextR\acontext\"0\n" +
	"\x15GetRoomContextRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"K\n" +
	"\x16GetRoomContextResponse\x121\n" +
	"\acontext\x18\x01 \x01(\v2\x17.context.v1.RoomContextR\acontext\"L\n" +
	"\x13IngestSignalRequest\x125\n" +
	"\x06signal\x18\x01 \x01(\v2\x1d.context.v1.EnvironmentSignalR\x06signal\".\n" +
	"\x14IngestSignalResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\":\n" +
	"\x19GetPresenceContextRequest\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\"S\n" +
	"\x1aGetPresenceContextResponse\x125\n" +
	"\acontext\x18\x01 \x01(\v2\x1b.context.v1.PresenceContextR\acontext2\xfa\x02\n" +
	"\x0eContextService\x12W\n" +
	"\x0eGetHomeContext\x12!.context.v1.GetHomeContextRequest\x1a\".context.v1.GetHomeContextResponse\x12W\n" +
	"\x0eGetRoomContext\x12!.context.v1.GetRoomContextRequest\x1a\".context.v1.GetRoomContextResponse\x12Q\n" +
	"\fIngestSignal\x12\x1f.context.v1.IngestSignalRequest\x1a .context.v1.IngestSignalResponse\x12c\n" +
	"\x12GetPresenceContext\x12%.context.v1.GetPresenceContextRequest\x1a&.context.v1.GetPresenceContextResponseB-Z+context-service/pkg/pb/context/v1;contextv1b\x06proto3"

var (
	file_context_v1_context_proto_rawDescOnce sync.Once
	file_context_v1_context_proto_rawDescData []byte
)

func file_context_v1_context_proto_rawDescGZIP() []byte {
	file_context_v1_context_proto_rawDescOnce.Do(func() {
		file_context_v1_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_context_v1_context_proto_rawDesc), len(file_context_v1_context_proto_rawDesc)))
	})
	return file_context_v1_context_proto_rawDescData
}

var file_context_v1_context_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_context_v1_context_proto_goTypes = []any{
	(*EnvironmentSignal)(nil),          // 0: context.v1.EnvironmentSignal
	(*HomeContext)(nil),                // 1: context.v1.HomeContext
	(*RoomContext)(nil),                // 2: context.v1.RoomContext
	(*PresenceContext)(nil),            // 3: context.v1.PresenceContext
	(*GetHomeContextRequest)(nil),      // 4: context.v1.GetHomeContextRequest
	(*GetHomeContextResponse)(nil),     // 5: context.v1.GetHomeContextResponse
	(*GetRoomContextRequest)(nil),      // 6: context.v1.GetRoomContextRequest
	(*GetRoomContextResponse)(nil),     // 7: context.v1.GetRoomContextResponse
	(*IngestSignalRequest)(nil),        // 8: context.v1.IngestSignalRequest
	(*IngestSignalResponse)(nil),       // 9: context.v1.IngestSignalResponse
	(*GetPresenceContextRequest)(nil),  // 10: context.v1.GetPresenceContextRequest
	(*GetPresenceContextResponse)(nil), // 11: context.v1.GetPresenceContextResponse
	(*timestamppb.Timestamp)(nil),      // 12: google.protobuf.Timestamp
}
var file_context_v1_context_proto_depIdxs = []int32{
	12, // 0: context.v1.EnvironmentSignal.observed_at:type_name -> google.protobuf.Timestamp
	12, // 1: context.v1.HomeContext.updated_at:type_name -> google.protobuf.Timestamp
	12, // 2: context.v1.RoomContext.updated_at:type_name -> google.protobuf.Timestamp
	12, // 3: context.v1.PresenceContext.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: context.v1.GetHomeContextResponse.context:type_name -> context.v1.HomeContext
	2,  // 5: context.v1.GetRoomContextResponse.context:type_name -> context.v1.RoomContext
	0,  // 6: context.v1.IngestSignalRequest.signal:type_name -> context.v1.EnvironmentSignal
	3,  // 7: context.v1.GetPresenceContextResponse.context:type_name -> context.v1.PresenceContext
	4,  // 8: context.v1.ContextService.GetHomeContext:input_type -> context.v1.GetHomeContextRequest
	6,  // 9: context.v1.ContextService.GetRoomContext:input_type -> context.v1.GetRoomContextRequest
	8,  // 10: context.v1.ContextService.IngestSignal:input_type -> context.v1.IngestSignalRequest
	10, // 11: context.v1.ContextService.GetPresenceContext:input_type -> context.v1.GetPresenceContextRequest
	5,  // 12: context.v1.ContextService.GetHomeContext:output_type -> context.v1.GetHomeContextResponse
	7,  // 13: context.v1.ContextService.GetRoomContext:output_type -> context.v1.GetRoomContextResponse
	9,  // 14: context.v1.ContextService.IngestSignal:output_type -> context.v1.IngestSignalResponse
	11, // 15: context.v1.ContextService.GetPresenceContext:output_type -> context.v1.GetPresenceContextResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_context_v1_context_proto_init() }
func file_context_v1_context_proto_init() {
	if File_context_v1_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_context_v1_context_proto_rawDesc), len(file_context_v1_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_context_v1_context_proto_goTypes,
		DependencyIndexes: file_context_v1_context_proto_depIdxs,
		MessageInfos:      file_context_v1_context_proto_msgTypes,
	}.Build()
	File_context_v1_context_proto = out.File
	file_context_v1_context_proto_goTypes = nil
	file_context_v1_context_proto_depIdxs = nil
}
