// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: context/v1/context.proto

package contextv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContextService_GetHomeContext_FullMethodName     = "/context.v1.ContextService/GetHomeContext"
	ContextService_GetRoomContext_FullMethodName     = "/context.v1.ContextService/GetRoomContext"
	ContextService_IngestSignal_FullMethodName       = "/context.v1.ContextService/IngestSignal"
	ContextService_GetPresenceContext_FullMethodName = "/context.v1.ContextService/GetPresenceContext"
)

// ContextServiceClient is the client API for ContextService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContextServiceClient interface {
	GetHomeContext(ctx context.Context, in *GetHomeContextRequest, opts ...grpc.CallOption) (*GetHomeContextResponse, error)
	GetRoomContext(ctx context.Context, in *GetRoomContextRequest, opts ...grpc.CallOption) (*GetRoomContextResponse, error)
	IngestSignal(ctx context.Context, in *IngestSignalRequest, opts ...grpc.CallOption) (*IngestSignalResponse, error)
	GetPresenceContext(ctx context.Context, in *GetPresenceContextRequest, opts ...grpc.CallOption) (*GetPresenceContextResponse, error)
}

type contextServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContextServiceClient(cc grpc.ClientConnInterface) ContextServiceClient {
	return &contextServiceClient{cc}
}

func (c *contextServiceClient) GetHomeContext(ctx context.Context, in *GetHomeContextRequest, opts ...grpc.CallOption) (*GetHomeContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHomeContextResponse)
	err := c.cc.Invoke(ctx, ContextService_GetHomeContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextServiceClient) GetRoomContext(ctx context.Context, in *GetRoomContextRequest, opts ...grpc.CallOption) (*GetRoomContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoomContextResponse)
	err := c.cc.Invoke(ctx, ContextService_GetRoomContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextServiceClient) IngestSignal(ctx context.Context, in *IngestSignalRequest, opts ...grpc.CallOption) (*IngestSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestSignalResponse)
	err := c.cc.Invoke(ctx, ContextService_IngestSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextServiceClient) GetPresenceContext(ctx context.Context, in *GetPresenceContextRequest, opts ...grpc.CallOption) (*GetPresenceContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPresenceContextResponse)
	err := c.cc.Invoke(ctx, ContextService_GetPresenceContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContextServiceServer is the server API for ContextService service.
// All implementations must embed UnimplementedContextServiceServer
// for forward compatibility.
type ContextServiceServer interface {
	GetHomeContext(context.Context, *GetHomeContextRequest) (*GetHomeContextResponse, error)
	GetRoomContext(context.Context, *GetRoomContextRequest) (*GetRoomContextResponse, error)
	IngestSignal(context.Context, *IngestSignalRequest) (*IngestSignalResponse, error)
	GetPresenceContext(context.Context, *GetPresenceContextRequest) (*GetPresenceContextResponse, error)
	mustEmbedUnimplementedContextServiceServer()
}

// UnimplementedContextServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContextServiceServer struct{}

func (UnimplementedContextServiceServer) GetHomeContext(context.Context, *GetHomeContextRequest) (*GetHomeContextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHomeContext not implemented")
}
func (UnimplementedContextServiceServer) GetRoomContext(context.Context, *GetRoomContextRequest) (*GetRoomContextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoomContext not implemented")
}
func (UnimplementedContextServiceServer) IngestSignal(context.Context, *IngestSignalRequest) (*IngestSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngestSignal not implemented")
}
func (UnimplementedContextServiceServer) GetPresenceContext(context.Context, *GetPresenceContextRequest) (*GetPresenceContextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPresenceContext not implemented")
}
func (UnimplementedContextServiceServer) mustEmbedUnimplementedContextServiceServer() {}
func (UnimplementedContextServiceServer) testEmbeddedByValue()                        {}

// UnsafeContextServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContextServiceServer will
// result in compilation errors.
type UnsafeContextServiceServer interface {
	mustEmbedUnimplementedContextServiceServer()
}

func RegisterContextServiceServer(s grpc.ServiceRegistrar, srv ContextServiceServer) {
	// If the following call pancis, it indicates UnimplementedContextServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContextService_ServiceDesc, srv)
}

func _ContextService_GetHomeContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHomeContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextServiceServer).GetHomeContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContextService_GetHomeContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextServiceServer).GetHomeContext(ctx, req.(*GetHomeContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextService_GetRoomContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextServiceServer).GetRoomContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContextService_GetRoomContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextServiceServer).GetRoomContext(ctx, req.(*GetRoomContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextService_IngestSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextServiceServer).IngestSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContextService_IngestSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextServiceServer).IngestSignal(ctx, req.(*IngestSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextService_GetPresenceContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPresenceContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextServiceServer).GetPresenceContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContextService_GetPresenceContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextServiceServer).GetPresenceContext(ctx, req.(*GetPresenceContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContextService_ServiceDesc is the grpc.ServiceDesc for ContextService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContextService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "context.v1.ContextService",
	HandlerType: (*ContextServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHomeContext",
			Handler:    _ContextService_GetHomeContext_Handler,
		},
		{
			MethodName: "GetRoomContext",
			Handler:    _ContextService_GetRoomContext_Handler,
		},
		{
			MethodName: "IngestSignal",
			Handler:    _ContextService_IngestSignal_Handler,
		},
		{
			MethodName: "GetPresenceContext",
			Handler:    _ContextService_GetPresenceContext_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "context/v1/context.proto",
}
