// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: edge_bridge/v1/edge_bridge.proto

package edgebridgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EdgeNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PublicAddr    string                 `protobuf:"bytes,3,opt,name=public_addr,json=publicAddr,proto3" json:"public_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeNode) Reset() {
	*x = EdgeNode{}
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeNode) ProtoMessage() {}

func (x *EdgeNode) ProtoReflect() protoreflect.Message {
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeNode.ProtoReflect.Descriptor instead.
func (*EdgeNode) Descriptor() ([]byte, []int) {
	return file_edge_bridge_v1_edge_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *EdgeNode) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *EdgeNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EdgeNode) GetPublicAddr() string {
	if x != nil {
		return x.PublicAddr
	}
	return ""
}

type EdgeRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeRoom) Reset() {
	*x = EdgeRoom{}
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeRoom) ProtoMessage() {}

func (x *EdgeRoom) ProtoReflect() protoreflect.Message {
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeRoom.ProtoReflect.Descriptor instead.
func (*EdgeRoom) Descriptor() ([]byte, []int) {
	return file_edge_bridge_v1_edge_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *EdgeRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *EdgeRoom) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EdgeDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	EntityId      string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	DeviceType    string                 `protobuf:"bytes,5,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	State         string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeDevice) Reset() {
	*x = EdgeDevice{}
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeDevice) ProtoMessage() {}

func (x *EdgeDevice) ProtoReflect() protoreflect.Message {
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeDevice.ProtoReflect.Descriptor instead.
func (*EdgeDevice) Descriptor() ([]byte, []int) {
	return file_edge_bridge_v1_edge_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *EdgeDevice) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *EdgeDevice) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *EdgeDevice) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *EdgeDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EdgeDevice) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *EdgeDevice) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type EdgeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EdgeId        string                 `protobuf:"bytes,2,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	EntityId      string                 `protobuf:"bytes,5,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EventType     string                 `protobuf:"bytes,6,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	State         string                 `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeEvent) Reset() {
	*x = EdgeEvent{}
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeEvent) ProtoMessage() {}

func (x *EdgeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeEvent.ProtoReflect.Descriptor instead.
func (*EdgeEvent) Descriptor() ([]byte, []int) {
	return file_edge_bridge_v1_edge_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *EdgeEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EdgeEvent) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *EdgeEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *EdgeEvent) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *EdgeEvent) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *EdgeEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EdgeEvent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *EdgeEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

type EdgeCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	EntityId      string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	TargetState   string                 `protobuf:"bytes,4,opt,name=target_state,json=targetState,proto3" json:"target_state,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeCommand) Reset() {
	*x = EdgeCommand{}
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeCommand) ProtoMessage() {}

func (x *EdgeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeCommand.ProtoReflect.Descriptor instead.
func (*EdgeCommand) Descriptor() ([]byte, []int) {
	return file_edge_bridge_v1_edge_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *EdgeCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *EdgeCommand) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *EdgeCommand) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *EdgeCommand) GetTargetState() string {
	if x != nil {
		return x.TargetState
	}
	return ""
}

func (x *EdgeCommand) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type OfflineScenario struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineScenario) Reset() {
	*x = OfflineScenario{}
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineScenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineScenario) ProtoMessage() {}

func (x *OfflineScenario) ProtoReflect() protoreflect.Message {
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineScenario.ProtoReflect.Descriptor instead.
func (*OfflineScenario) Descriptor() ([]byte, []int) {
	return file_edge_bridge_v1_edge_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *OfflineScenario) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *OfflineScenario) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OfflineScenario) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type RegisterEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edge          *EdgeNode              `protobuf:"bytes,1,opt,name=edge,proto3" json:"edge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterEdgeRequest) Reset() {
	*x = RegisterEdgeRequest{}
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEdgeRequest) ProtoMessage() {}

func (x *RegisterEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEdgeRequest.ProtoReflect.Descriptor instead.
func (*RegisterEdgeRequest) Descriptor() ([]byte, []int) {
	return file_edge_bridge_v1_edge_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterEdgeRequest) GetEdge() *EdgeNode {
	if x != nil {
		return x.Edge
	}
	return nil
}

type RegisterEdgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterEdgeResponse) Reset() {
	*x = RegisterEdgeResponse{}
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEdgeResponse) ProtoMessage() {}

func (x *RegisterEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEdgeResponse.ProtoReflect.Descriptor instead.
func (*RegisterEdgeResponse) Descriptor() ([]byte, []int) {
	return file_edge_bridge_v1_edge_bridge_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterEdgeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SyncInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	Rooms         []*EdgeRoom            `protobuf:"bytes,2,rep,name=rooms,proto3" json:"rooms,omitempty"`
	Devices       []*EdgeDevice          `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncInventoryRequest) Reset() {
	*x = SyncInventoryRequest{}
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncInventoryRequest) ProtoMessage() {}

func (x *SyncInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncInventoryRequest.ProtoReflect.Descriptor instead.
func (*SyncInventoryRequest) Descriptor() ([]byte, []int) {
	return file_edge_bridge_v1_edge_bridge_proto_rawDescGZIP(), []int{8}
}

func (x *SyncInventoryRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *SyncInventoryRequest) GetRooms() []*EdgeRoom {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *SyncInventoryRequest) GetDevices() []*EdgeDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

type SyncInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncId        string                 `protobuf:"bytes,1,opt,name=sync_id,json=syncId,proto3" json:"sync_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncInventoryResponse) Reset() {
	*x = SyncInventoryResponse{}
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncInventoryResponse) ProtoMessage() {}

func (x *SyncInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncInventoryResponse.ProtoReflect.Descriptor instead.
func (*SyncInventoryResponse) Descriptor() ([]byte, []int) {
	return file_edge_bridge_v1_edge_bridge_proto_rawDescGZIP(), []int{9}
}

func (x *SyncInventoryResponse) GetSyncId() string {
	if x != nil {
		return x.SyncId
	}
	return ""
}

func (x *SyncInventoryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PublishEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *EdgeEvent             `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventRequest) Reset() {
	*x = PublishEventRequest{}
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventRequest) ProtoMessage() {}

func (x *PublishEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventRequest.ProtoReflect.Descriptor instead.
func (*PublishEventRequest) Descriptor() ([]byte, []int) {
	return file_edge_bridge_v1_edge_bridge_proto_rawDescGZIP(), []int{10}
}

func (x *PublishEventRequest) GetEvent() *EdgeEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type PublishEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventResponse) Reset() {
	*x = PublishEventResponse{}
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventResponse) ProtoMessage() {}

func (x *PublishEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventResponse.ProtoReflect.Descriptor instead.
func (*PublishEventResponse) Descriptor() ([]byte, []int) {
	return file_edge_bridge_v1_edge_bridge_proto_rawDescGZIP(), []int{11}
}

func (x *PublishEventResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PollCommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollCommandsRequest) Reset() {
	*x = PollCommandsRequest{}
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollCommandsRequest) ProtoMessage() {}

func (x *PollCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollCommandsRequest.ProtoReflect.Descriptor instead.
func (*PollCommandsRequest) Descriptor() ([]byte, []int) {
	return file_edge_bridge_v1_edge_bridge_proto_rawDescGZIP(), []int{12}
}

func (x *PollCommandsRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

type PollCommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*EdgeCommand         `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollCommandsResponse) Reset() {
	*x = PollCommandsResponse{}
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollCommandsResponse) ProtoMessage() {}

func (x *PollCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollCommandsResponse.ProtoReflect.Descriptor instead.
func (*PollCommandsResponse) Descriptor() ([]byte, []int) {
	return file_edge_bridge_v1_edge_bridge_proto_rawDescGZIP(), []int{13}
}

func (x *PollCommandsResponse) GetCommands() []*EdgeCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

type GetOfflineScenariosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOfflineScenariosRequest) Reset() {
	*x = GetOfflineScenariosRequest{}
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOfflineScenariosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfflineScenariosRequest) ProtoMessage() {}

func (x *GetOfflineScenariosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfflineScenariosRequest.ProtoReflect.Descriptor instead.
func (*GetOfflineScenariosRequest) Descriptor() ([]byte, []int) {
	return file_edge_bridge_v1_edge_bridge_proto_rawDescGZIP(), []int{14}
}

func (x *GetOfflineScenariosRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

type GetOfflineScenariosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenarios     []*OfflineScenario     `protobuf:"bytes,1,rep,name=scenarios,proto3" json:"scenarios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOfflineScenariosResponse) Reset() {
	*x = GetOfflineScenariosResponse{}
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOfflineScenariosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfflineScenariosResponse) ProtoMessage() {}

func (x *GetOfflineScenariosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edge_bridge_v1_edge_bridge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfflineScenariosResponse.ProtoReflect.Descriptor instead.
func (*GetOfflineScenariosResponse) Descriptor() ([]byte, []int) {
	return file_edge_bridge_v1_edge_bridge_proto_rawDescGZIP(), []int{15}
}

func (x *GetOfflineScenariosResponse) GetScenarios() []*OfflineScenario {
	if x != nil {
		return x.Scenarios
	}
	return nil
}

var File_edge_bridge_v1_edge_bridge_proto protoreflect.FileDescriptor

const file_edge_bridge_v1_edge_bridge_proto_rawDesc = "" +
	"\n" +
	" edge_bridge/v1/edge_bridge.proto\x12\x0eedge_bridge.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"X\n" +
	"\bEdgeNode\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vpublic_addr\x18\x03 \x01(\tR\n" +
	"publicAddr\"7\n" +
	"\bEdgeRoom\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xaa\x01\n" +
	"\n" +
	"EdgeDevice\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1f\n" +
	"\vdevice_type\x18\x05 \x01(\tR\n" +
	"deviceType\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\"\x84\x02\n" +
	"\tEdgeEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\aedge_id\x18\x02 \x01(\tR\x06edgeId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tentity_id\x18\x05 \x01(\tR\bentityId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x06 \x01(\tR\teventType\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\x12;\n" +
	"\voccurred_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xa1\x01\n" +
	"\vEdgeCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12!\n" +
	"\ftarget_state\x18\x04 \x01(\tR\vtargetState\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"b\n" +
	"\x0fOfflineScenario\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\"C\n" +
	"\x13RegisterEdgeRequest\x12,\n" +
	"\x04edge\x18\x01 \x01(\v2\x18.edge_bridge.v1.EdgeNodeR\x04edge\".\n" +
	"\x14RegisterEdgeResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x95\x01\n" +
	"\x14SyncInventoryRequest\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12.\n" +
	"\x05rooms\x18\x02 \x03(\v2\x18.edge_bridge.v1.EdgeRoomR\x05rooms\x124\n" +
	"\adevices\x18\x03 \x03(\v2\x1a.edge_bridge.v1.EdgeDeviceR\adevices\"H\n" +
	"\x15SyncInventoryResponse\x12\x17\n" +
	"\async_id\x18\x01 \x01(\tR\x06syncId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"F\n" +
	"\x13PublishEventRequest\x12/\n" +
	"\x05event\x18\x01 \x01(\v2\x19.edge_bridge.v1.EdgeEventR\x05event\".\n" +
	"\x14PublishEventResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\".\n" +
	"\x13PollCommandsRequest\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\"O\n" +
	"\x14PollCommandsResponse\x127\n" +
	"\bcommands\x18\x01 \x03(\v2\x1b.edge_bridge.v1.EdgeCommandR\bcommands\"5\n" +
	"\x1aGetOfflineScenariosRequest\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\"\\\n" +
	"\x1bGetOfflineScenariosResponse\x12=\n" +
	"\tscenarios\x18\x01 \x03(\v2\x1f.edge_bridge.v1.OfflineScenarioR\tscenarios2\xf2\x03\n" +
	"\x11EdgeBridgeService\x12Y\n" +
	"\fRegisterEdge\x12#.edge_bridge.v1.RegisterEdgeRequest\x1a$.edge_bridge.v1.RegisterEdgeResponse\x12\\\n" +
	"\rSyncInventory\x12$.edge_bridge.v1.SyncInventoryRequest\x1a%.edge_bridge.v1.SyncInventoryResponse\x12Y\n" +
	"\fPublishEvent\x12#.edge_bridge.v1.PublishEventRequest\x1a$.edge_bridge.v1.PublishEventResponse\x12Y\n" +
	"\fPollCommands\x12#.edge_bridge.v1.PollCommandsRequest\x1a$.edge_bridge.v1.PollCommandsResponse\x12n\n" +
	"\x13GetOfflineScenarios\x12*.edge_bridge.v1.GetOfflineScenariosRequest\x1a+.edge_bridge.v1.GetOfflineScenariosResponseB8Z6edge-bridge-service/pkg/pb/edge_bridge/v1;edgebridgev1b\x06proto3"

var (
	file_edge_bridge_v1_edge_bridge_proto_rawDescOnce sync.Once
	file_edge_bridge_v1_edge_bridge_proto_rawDescData []byte
)

func file_edge_bridge_v1_edge_bridge_proto_rawDescGZIP() []byte {
	file_edge_bridge_v1_edge_bridge_proto_rawDescOnce.Do(func() {
		file_edge_bridge_v1_edge_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_edge_bridge_v1_edge_bridge_proto_rawDesc), len(file_edge_bridge_v1_edge_bridge_proto_rawDesc)))
	})
	return file_edge_bridge_v1_edge_bridge_proto_rawDescData
}

var file_edge_bridge_v1_edge_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_edge_bridge_v1_edge_bridge_proto_goTypes = []any{
	(*EdgeNode)(nil),                    // 0: edge_bridge.v1.EdgeNode
	(*EdgeRoom)(nil),                    // 1: edge_bridge.v1.EdgeRoom
	(*EdgeDevice)(nil),                  // 2: edge_bridge.v1.EdgeDevice
	(*EdgeEvent)(nil),                   // 3: edge_bridge.v1.EdgeEvent
	(*EdgeCommand)(nil),                 // 4: edge_bridge.v1.EdgeCommand
	(*OfflineScenario)(nil),             // 5: edge_bridge.v1.OfflineScenario
	(*RegisterEdgeRequest)(nil),         // 6: edge_bridge.v1.RegisterEdgeRequest
	(*RegisterEdgeResponse)(nil),        // 7: edge_bridge.v1.RegisterEdgeResponse
	(*SyncInventoryRequest)(nil),        // 8: edge_bridge.v1.SyncInventoryRequest
	(*SyncInventoryResponse)(nil),       // 9: edge_bridge.v1.SyncInventoryResponse
	(*PublishEventRequest)(nil),         // 10: edge_bridge.v1.PublishEventRequest
	(*PublishEventResponse)(nil),        // 11: edge_bridge.v1.PublishEventResponse
	(*PollCommandsRequest)(nil),         // 12: edge_bridge.v1.PollCommandsRequest
	(*PollCommandsResponse)(nil),        // 13: edge_bridge.v1.PollCommandsResponse
	(*GetOfflineScenariosRequest)(nil),  // 14: edge_bridge.v1.GetOfflineScenariosRequest
	(*GetOfflineScenariosResponse)(nil), // 15: edge_bridge.v1.GetOfflineScenariosResponse
	(*timestamppb.Timestamp)(nil),       // 16: google.protobuf.Timestamp
}
var file_edge_bridge_v1_edge_bridge_proto_depIdxs = []int32{
	16, // 0: edge_bridge.v1.EdgeEvent.occurred_at:type_name -> google.protobuf.Timestamp
	0,  // 1: edge_bridge.v1.RegisterEdgeRequest.edge:type_name -> edge_bridge.v1.EdgeNode
	1,  // 2: edge_bridge.v1.SyncInventoryRequest.rooms:type_name -> edge_bridge.v1.EdgeRoom
	2,  // 3: edge_bridge.v1.SyncInventoryRequest.devices:type_name -> edge_bridge.v1.EdgeDevice
	3,  // 4: edge_bridge.v1.PublishEventRequest.event:type_name -> edge_bridge.v1.EdgeEvent
	4,  // 5: edge_bridge.v1.PollCommandsResponse.commands:type_name -> edge_bridge.v1.EdgeCommand
	5,  // 6: edge_bridge.v1.GetOfflineScenariosResponse.scenarios:type_name -> edge_bridge.v1.OfflineScenario
	6,  // 7: edge_bridge.v1.EdgeBridgeService.RegisterEdge:input_type -> edge_bridge.v1.RegisterEdgeRequest
	8,  // 8: edge_bridge.v1.EdgeBridgeService.SyncInventory:input_type -> edge_bridge.v1.SyncInventoryRequest
	10, // 9: edge_bridge.v1.EdgeBridgeService.PublishEvent:input_type -> edge_bridge.v1.PublishEventRequest
	12, // 10: edge_bridge.v1.EdgeBridgeService.PollCommands:input_type -> edge_bridge.v1.PollCommandsRequest
	14, // 11: edge_bridge.v1.EdgeBridgeService.GetOfflineScenarios:input_type -> edge_bridge.v1.GetOfflineScenariosRequest
	7,  // 12: edge_bridge.v1.EdgeBridgeService.RegisterEdge:output_type -> edge_bridge.v1.RegisterEdgeResponse
	9,  // 13: edge_bridge.v1.EdgeBridgeService.SyncInventory:output_type -> edge_bridge.v1.SyncInventoryResponse
	11, // 14: edge_bridge.v1.EdgeBridgeService.PublishEvent:output_type -> edge_bridge.v1.PublishEventResponse
	13, // 15: edge_bridge.v1.EdgeBridgeService.PollCommands:output_type -> edge_bridge.v1.PollCommandsResponse
	15, // 16: edge_bridge.v1.EdgeBridgeService.GetOfflineScenarios:output_type -> edge_bridge.v1.GetOfflineScenariosResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_edge_bridge_v1_edge_bridge_proto_init() }
func file_edge_bridge_v1_edge_bridge_proto_init() {
	if File_edge_bridge_v1_edge_bridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_edge_bridge_v1_edge_bridge_proto_rawDesc), len(file_edge_bridge_v1_edge_bridge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_edge_bridge_v1_edge_bridge_proto_goTypes,
		DependencyIndexes: file_edge_bridge_v1_edge_bridge_proto_depIdxs,
		MessageInfos:      file_edge_bridge_v1_edge_bridge_proto_msgTypes,
	}.Build()
	File_edge_bridge_v1_edge_bridge_proto = out.File
	file_edge_bridge_v1_edge_bridge_proto_goTypes = nil
	file_edge_bridge_v1_edge_bridge_proto_depIdxs = nil
}
