// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: edge_bridge/v1/edge_bridge.proto

package edgebridgev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EdgeBridgeService_RegisterEdge_FullMethodName        = "/edge_bridge.v1.EdgeBridgeService/RegisterEdge"
	EdgeBridgeService_SyncInventory_FullMethodName       = "/edge_bridge.v1.EdgeBridgeService/SyncInventory"
	EdgeBridgeService_PublishEvent_FullMethodName        = "/edge_bridge.v1.EdgeBridgeService/PublishEvent"
	EdgeBridgeService_PollCommands_FullMethodName        = "/edge_bridge.v1.EdgeBridgeService/PollCommands"
	EdgeBridgeService_GetOfflineScenarios_FullMethodName = "/edge_bridge.v1.EdgeBridgeService/GetOfflineScenarios"
)

// EdgeBridgeServiceClient is the client API for EdgeBridgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EdgeBridgeServiceClient interface {
	RegisterEdge(ctx context.Context, in *RegisterEdgeRequest, opts ...grpc.CallOption) (*RegisterEdgeResponse, error)
	SyncInventory(ctx context.Context, in *SyncInventoryRequest, opts ...grpc.CallOption) (*SyncInventoryResponse, error)
	PublishEvent(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*PublishEventResponse, error)
	PollCommands(ctx context.Context, in *PollCommandsRequest, opts ...grpc.CallOption) (*PollCommandsResponse, error)
	GetOfflineScenarios(ctx context.Context, in *GetOfflineScenariosRequest, opts ...grpc.CallOption) (*GetOfflineScenariosResponse, error)
}

type edgeBridgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEdgeBridgeServiceClient(cc grpc.ClientConnInterface) EdgeBridgeServiceClient {
	return &edgeBridgeServiceClient{cc}
}

func (c *edgeBridgeServiceClient) RegisterEdge(ctx context.Context, in *RegisterEdgeRequest, opts ...grpc.CallOption) (*RegisterEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterEdgeResponse)
	err := c.cc.Invoke(ctx, EdgeBridgeService_RegisterEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeBridgeServiceClient) SyncInventory(ctx context.Context, in *SyncInventoryRequest, opts ...grpc.CallOption) (*SyncInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncInventoryResponse)
	err := c.cc.Invoke(ctx, EdgeBridgeService_SyncInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeBridgeServiceClient) PublishEvent(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*PublishEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishEventResponse)
	err := c.cc.Invoke(ctx, EdgeBridgeService_PublishEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeBridgeServiceClient) PollCommands(ctx context.Context, in *PollCommandsRequest, opts ...grpc.CallOption) (*PollCommandsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollCommandsResponse)
	err := c.cc.Invoke(ctx, EdgeBridgeService_PollCommands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeBridgeServiceClient) GetOfflineScenarios(ctx context.Context, in *GetOfflineScenariosRequest, opts ...grpc.CallOption) (*GetOfflineScenariosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOfflineScenariosResponse)
	err := c.cc.Invoke(ctx, EdgeBridgeService_GetOfflineScenarios_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EdgeBridgeServiceServer is the server API for EdgeBridgeService service.
// All implementations must embed UnimplementedEdgeBridgeServiceServer
// for forward compatibility.
type EdgeBridgeServiceServer interface {
	RegisterEdge(context.Context, *RegisterEdgeRequest) (*RegisterEdgeResponse, error)
	SyncInventory(context.Context, *SyncInventoryRequest) (*SyncInventoryResponse, error)
	PublishEvent(context.Context, *PublishEventRequest) (*PublishEventResponse, error)
	PollCommands(context.Context, *PollCommandsRequest) (*PollCommandsResponse, error)
	GetOfflineScenarios(context.Context, *GetOfflineScenariosRequest) (*GetOfflineScenariosResponse, error)
	mustEmbedUnimplementedEdgeBridgeServiceServer()
}

// UnimplementedEdgeBridgeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEdgeBridgeServiceServer struct{}

func (UnimplementedEdgeBridgeServiceServer) RegisterEdge(context.Context, *RegisterEdgeRequest) (*RegisterEdgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterEdge not implemented")
}
func (UnimplementedEdgeBridgeServiceServer) SyncInventory(context.Context, *SyncInventoryRequest) (*SyncInventoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncInventory not implemented")
}
func (UnimplementedEdgeBridgeServiceServer) PublishEvent(context.Context, *PublishEventRequest) (*PublishEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishEvent not implemented")
}
func (UnimplementedEdgeBridgeServiceServer) PollCommands(context.Context, *PollCommandsRequest) (*PollCommandsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PollCommands not implemented")
}
func (UnimplementedEdgeBridgeServiceServer) GetOfflineScenarios(context.Context, *GetOfflineScenariosRequest) (*GetOfflineScenariosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOfflineScenarios not implemented")
}
func (UnimplementedEdgeBridgeServiceServer) mustEmbedUnimplementedEdgeBridgeServiceServer() {}
func (UnimplementedEdgeBridgeServiceServer) testEmbeddedByValue()                           {}

// UnsafeEdgeBridgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EdgeBridgeServiceServer will
// result in compilation errors.
type UnsafeEdgeBridgeServiceServer interface {
	mustEmbedUnimplementedEdgeBridgeServiceServer()
}

func RegisterEdgeBridgeServiceServer(s grpc.ServiceRegistrar, srv EdgeBridgeServiceServer) {
	// If the following call pancis, it indicates UnimplementedEdgeBridgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EdgeBridgeService_ServiceDesc, srv)
}

func _EdgeBridgeService_RegisterEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeBridgeServiceServer).RegisterEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeBridgeService_RegisterEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeBridgeServiceServer).RegisterEdge(ctx, req.(*RegisterEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeBridgeService_SyncInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeBridgeServiceServer).SyncInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeBridgeService_SyncInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeBridgeServiceServer).SyncInventory(ctx, req.(*SyncInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeBridgeService_PublishEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeBridgeServiceServer).PublishEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeBridgeService_PublishEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeBridgeServiceServer).PublishEvent(ctx, req.(*PublishEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeBridgeService_PollCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeBridgeServiceServer).PollCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeBridgeService_PollCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeBridgeServiceServer).PollCommands(ctx, req.(*PollCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeBridgeService_GetOfflineScenarios_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOfflineScenariosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeBridgeServiceServer).GetOfflineScenarios(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeBridgeService_GetOfflineScenarios_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeBridgeServiceServer).GetOfflineScenarios(ctx, req.(*GetOfflineScenariosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EdgeBridgeService_ServiceDesc is the grpc.ServiceDesc for EdgeBridgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EdgeBridgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "edge_bridge.v1.EdgeBridgeService",
	HandlerType: (*EdgeBridgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterEdge",
			Handler:    _EdgeBridgeService_RegisterEdge_Handler,
		},
		{
			MethodName: "SyncInventory",
			Handler:    _EdgeBridgeService_SyncInventory_Handler,
		},
		{
			MethodName: "PublishEvent",
			Handler:    _EdgeBridgeService_PublishEvent_Handler,
		},
		{
			MethodName: "PollCommands",
			Handler:    _EdgeBridgeService_PollCommands_Handler,
		},
		{
			MethodName: "GetOfflineScenarios",
			Handler:    _EdgeBridgeService_GetOfflineScenarios_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "edge_bridge/v1/edge_bridge.proto",
}
