// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: device/v1/device.proto

package devicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Floor         string                 `protobuf:"bytes,3,opt,name=floor,proto3" json:"floor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_device_v1_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetFloor() string {
	if x != nil {
		return x.Floor
	}
	return ""
}

type Device struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceId       string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	EdgeId         string                 `protobuf:"bytes,2,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	RoomId         string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	DeviceType     string                 `protobuf:"bytes,5,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	EntityId       string                 `protobuf:"bytes,6,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	State          string                 `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	OfflineCapable bool                   `protobuf:"varint,8,opt,name=offline_capable,json=offlineCapable,proto3" json:"offline_capable,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_device_v1_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{1}
}

func (x *Device) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Device) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *Device) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *Device) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Device) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Device) GetOfflineCapable() bool {
	if x != nil {
		return x.OfflineCapable
	}
	return false
}

func (x *Device) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeviceState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	ChangedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceState) Reset() {
	*x = DeviceState{}
	mi := &file_device_v1_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceState) ProtoMessage() {}

func (x *DeviceState) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceState.ProtoReflect.Descriptor instead.
func (*DeviceState) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceState) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceState) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *DeviceState) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *DeviceState) GetChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangedAt
	}
	return nil
}

type ListRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsRequest) Reset() {
	*x = ListRoomsRequest{}
	mi := &file_device_v1_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsRequest) ProtoMessage() {}

func (x *ListRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsRequest.ProtoReflect.Descriptor instead.
func (*ListRoomsRequest) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{3}
}

func (x *ListRoomsRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

type ListRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*Room                `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsResponse) Reset() {
	*x = ListRoomsResponse{}
	mi := &file_device_v1_device_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsResponse) ProtoMessage() {}

func (x *ListRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsResponse.ProtoReflect.Descriptor instead.
func (*ListRoomsResponse) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{4}
}

func (x *ListRoomsResponse) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_device_v1_device_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{5}
}

func (x *ListDevicesRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *ListDevicesRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_device_v1_device_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{6}
}

func (x *ListDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type GetDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceRequest) Reset() {
	*x = GetDeviceRequest{}
	mi := &file_device_v1_device_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceRequest) ProtoMessage() {}

func (x *GetDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceRequest) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{7}
}

func (x *GetDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type GetDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceResponse) Reset() {
	*x = GetDeviceResponse{}
	mi := &file_device_v1_device_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceResponse) ProtoMessage() {}

func (x *GetDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceResponse) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{8}
}

func (x *GetDeviceResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type SyncInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	Rooms         []*Room                `protobuf:"bytes,2,rep,name=rooms,proto3" json:"rooms,omitempty"`
	Devices       []*Device              `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncInventoryRequest) Reset() {
	*x = SyncInventoryRequest{}
	mi := &file_device_v1_device_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncInventoryRequest) ProtoMessage() {}

func (x *SyncInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncInventoryRequest.ProtoReflect.Descriptor instead.
func (*SyncInventoryRequest) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{9}
}

func (x *SyncInventoryRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *SyncInventoryRequest) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *SyncInventoryRequest) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type SyncInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncId        string                 `protobuf:"bytes,1,opt,name=sync_id,json=syncId,proto3" json:"sync_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncInventoryResponse) Reset() {
	*x = SyncInventoryResponse{}
	mi := &file_device_v1_device_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncInventoryResponse) ProtoMessage() {}

func (x *SyncInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncInventoryResponse.ProtoReflect.Descriptor instead.
func (*SyncInventoryResponse) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{10}
}

func (x *SyncInventoryResponse) GetSyncId() string {
	if x != nil {
		return x.SyncId
	}
	return ""
}

func (x *SyncInventoryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpsertDeviceStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	State         *DeviceState           `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertDeviceStateRequest) Reset() {
	*x = UpsertDeviceStateRequest{}
	mi := &file_device_v1_device_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertDeviceStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDeviceStateRequest) ProtoMessage() {}

func (x *UpsertDeviceStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDeviceStateRequest.ProtoReflect.Descriptor instead.
func (*UpsertDeviceStateRequest) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{11}
}

func (x *UpsertDeviceStateRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *UpsertDeviceStateRequest) GetState() *DeviceState {
	if x != nil {
		return x.State
	}
	return nil
}

type UpsertDeviceStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertDeviceStateResponse) Reset() {
	*x = UpsertDeviceStateResponse{}
	mi := &file_device_v1_device_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertDeviceStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDeviceStateResponse) ProtoMessage() {}

func (x *UpsertDeviceStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDeviceStateResponse.ProtoReflect.Descriptor instead.
func (*UpsertDeviceStateResponse) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{12}
}

func (x *UpsertDeviceStateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ExecuteCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	EntityId      string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	TargetState   string                 `protobuf:"bytes,4,opt,name=target_state,json=targetState,proto3" json:"target_state,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandRequest) Reset() {
	*x = ExecuteCommandRequest{}
	mi := &file_device_v1_device_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandRequest) ProtoMessage() {}

func (x *ExecuteCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandRequest.ProtoReflect.Descriptor instead.
func (*ExecuteCommandRequest) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{13}
}

func (x *ExecuteCommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ExecuteCommandRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ExecuteCommandRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ExecuteCommandRequest) GetTargetState() string {
	if x != nil {
		return x.TargetState
	}
	return ""
}

func (x *ExecuteCommandRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ExecuteCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandResponse) Reset() {
	*x = ExecuteCommandResponse{}
	mi := &file_device_v1_device_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandResponse) ProtoMessage() {}

func (x *ExecuteCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandResponse.ProtoReflect.Descriptor instead.
func (*ExecuteCommandResponse) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{14}
}

func (x *ExecuteCommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ExecuteCommandResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_device_v1_device_proto protoreflect.FileDescriptor

const file_device_v1_device_proto_rawDesc = "" +
	"\n" +
	"\x16device/v1/device.proto\x12\tdevice.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"I\n" +
	"\x04Room\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05floor\x18\x03 \x01(\tR\x05floor\"\xa3\x02\n" +
	"\x06Device\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x17\n" +
	"\aedge_id\x18\x02 \x01(\tR\x06edgeId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1f\n" +
	"\vdevice_type\x18\x05 \x01(\tR\n" +
	"deviceType\x12\x1b\n" +
	"\tentity_id\x18\x06 \x01(\tR\bentityId\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\x12'\n" +
	"\x0foffline_capable\x18\b \x01(\bR\x0eofflineCapable\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x98\x01\n" +
	"\vDeviceState\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x129\n" +
	"\n" +
	"changed_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tchangedAt\"+\n" +
	"\x10ListRoomsRequest\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\":\n" +
	"\x11ListRoomsResponse\x12%\n" +
	"\x05rooms\x18\x01 \x03(\v2\x0f.device.v1.RoomR\x05rooms\"F\n" +
	"\x12ListDevicesRequest\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"B\n" +
	"\x13ListDevicesResponse\x12+\n" +
	"\adevices\x18\x01 \x03(\v2\x11.device.v1.DeviceR\adevices\"/\n" +
	"\x10GetDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\">\n" +
	"\x11GetDeviceResponse\x12)\n" +
	"\x06device\x18\x01 \x01(\v2\x11.device.v1.DeviceR\x06device\"\x83\x01\n" +
	"\x14SyncInventoryRequest\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12%\n" +
	"\x05rooms\x18\x02 \x03(\v2\x0f.device.v1.RoomR\x05rooms\x12+\n" +
	"\adevices\x18\x03 \x03(\v2\x11.device.v1.DeviceR\adevices\"H\n" +
	"\x15SyncInventoryResponse\x12\x17\n" +
	"\async_id\x18\x01 \x01(\tR\x06syncId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"a\n" +
	"\x18UpsertDeviceStateRequest\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12,\n" +
	"\x05state\x18\x02 \x01(\v2\x16.device.v1.DeviceStateR\x05state\"3\n" +
	"\x19UpsertDeviceStateResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xab\x01\n" +
	"\x15ExecuteCommandRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12!\n" +
	"\ftarget_state\x18\x04 \x01(\tR\vtargetState\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"O\n" +
	"\x16ExecuteCommandResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xf8\x03\n" +
	"\rDeviceService\x12F\n" +
	"\tListRooms\x12\x1b.device.v1.ListRoomsRequest\x1a\x1c.device.v1.ListRoomsResponse\x12L\n" +
	"\vListDevices\x12\x1d.device.v1.ListDevicesRequest\x1a\x1e.device.v1.ListDevicesResponse\x12F\n" +
	"\tGetDevice\x12\x1b.device.v1.GetDeviceRequest\x1a\x1c.device.v1.GetDeviceResponse\x12R\n" +
	"\rSyncInventory\x12\x1f.device.v1.SyncInventoryRequest\x1a .device.v1.SyncInventoryResponse\x12^\n" +
	"\x11UpsertDeviceState\x12#.device.v1.UpsertDeviceStateRequest\x1a$.device.v1.UpsertDeviceStateResponse\x12U\n" +
	"\x0eExecuteCommand\x12 .device.v1.ExecuteCommandRequest\x1a!.device.v1.ExecuteCommandResponseB*Z(device-service/pkg/pb/device/v1;devicev1b\x06proto3"

var (
	file_device_v1_device_proto_rawDescOnce sync.Once
	file_device_v1_device_proto_rawDescData []byte
)

func file_device_v1_device_proto_rawDescGZIP() []byte {
	file_device_v1_device_proto_rawDescOnce.Do(func() {
		file_device_v1_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_device_v1_device_proto_rawDesc), len(file_device_v1_device_proto_rawDesc)))
	})
	return file_device_v1_device_proto_rawDescData
}

var file_device_v1_device_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_device_v1_device_proto_goTypes = []any{
	(*Room)(nil),                      // 0: device.v1.Room
	(*Device)(nil),                    // 1: device.v1.Device
	(*DeviceState)(nil),               // 2: device.v1.DeviceState
	(*ListRoomsRequest)(nil),          // 3: device.v1.ListRoomsRequest
	(*ListRoomsResponse)(nil),         // 4: device.v1.ListRoomsResponse
	(*ListDevicesRequest)(nil),        // 5: device.v1.ListDevicesRequest
	(*ListDevicesResponse)(nil),       // 6: device.v1.ListDevicesResponse
	(*GetDeviceRequest)(nil),          // 7: device.v1.GetDeviceRequest
	(*GetDeviceResponse)(nil),         // 8: device.v1.GetDeviceResponse
	(*SyncInventoryRequest)(nil),      // 9: device.v1.SyncInventoryRequest
	(*SyncInventoryResponse)(nil),     // 10: device.v1.SyncInventoryResponse
	(*UpsertDeviceStateRequest)(nil),  // 11: device.v1.UpsertDeviceStateRequest
	(*UpsertDeviceStateResponse)(nil), // 12: device.v1.UpsertDeviceStateResponse
	(*ExecuteCommandRequest)(nil),     // 13: device.v1.ExecuteCommandRequest
	(*ExecuteCommandResponse)(nil),    // 14: device.v1.ExecuteCommandResponse
	(*timestamppb.Timestamp)(nil),     // 15: google.protobuf.Timestamp
}
var file_device_v1_device_proto_depIdxs = []int32{
	15, // 0: device.v1.Device.updated_at:type_name -> google.protobuf.Timestamp
	15, // 1: device.v1.DeviceState.changed_at:type_name -> google.protobuf.Timestamp
	0,  // 2: device.v1.ListRoomsResponse.rooms:type_name -> device.v1.Room
	1,  // 3: device.v1.ListDevicesResponse.devices:type_name -> device.v1.Device
	1,  // 4: device.v1.GetDeviceResponse.device:type_name -> device.v1.Device
	0,  // 5: device.v1.SyncInventoryRequest.rooms:type_name -> device.v1.Room
	1,  // 6: device.v1.SyncInventoryRequest.devices:type_name -> device.v1.Device
	2,  // 7: device.v1.UpsertDeviceStateRequest.state:type_name -> device.v1.DeviceState
	3,  // 8: device.v1.DeviceService.ListRooms:input_type -> device.v1.ListRoomsRequest
	5,  // 9: device.v1.DeviceService.ListDevices:input_type -> device.v1.ListDevicesRequest
	7,  // 10: device.v1.DeviceService.GetDevice:input_type -> device.v1.GetDeviceRequest
	9,  // 11: device.v1.DeviceService.SyncInventory:input_type -> device.v1.SyncInventoryRequest
	11, // 12: device.v1.DeviceService.UpsertDeviceState:input_type -> device.v1.UpsertDeviceStateRequest
	13, // 13: device.v1.DeviceService.ExecuteCommand:input_type -> device.v1.ExecuteCommandRequest
	4,  // 14: device.v1.DeviceService.ListRooms:output_type -> device.v1.ListRoomsResponse
	6,  // 15: device.v1.DeviceService.ListDevices:output_type -> device.v1.ListDevicesResponse
	8,  // 16: device.v1.DeviceService.GetDevice:output_type -> device.v1.GetDeviceResponse
	10, // 17: device.v1.DeviceService.SyncInventory:output_type -> device.v1.SyncInventoryResponse
	12, // 18: device.v1.DeviceService.UpsertDeviceState:output_type -> device.v1.UpsertDeviceStateResponse
	14, // 19: device.v1.DeviceService.ExecuteCommand:output_type -> device.v1.ExecuteCommandResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_device_v1_device_proto_init() }
func file_device_v1_device_proto_init() {
	if File_device_v1_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_device_v1_device_proto_rawDesc), len(file_device_v1_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_device_v1_device_proto_goTypes,
		DependencyIndexes: file_device_v1_device_proto_depIdxs,
		MessageInfos:      file_device_v1_device_proto_msgTypes,
	}.Build()
	File_device_v1_device_proto = out.File
	file_device_v1_device_proto_goTypes = nil
	file_device_v1_device_proto_depIdxs = nil
}
