// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: vision/v1/vision.proto

package visionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VisionService_AnalyzeFrame_FullMethodName      = "/vision.v1.VisionService/AnalyzeFrame"
	VisionService_DetectAccessEvent_FullMethodName = "/vision.v1.VisionService/DetectAccessEvent"
)

// VisionServiceClient is the client API for VisionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VisionServiceClient interface {
	AnalyzeFrame(ctx context.Context, in *AnalyzeFrameRequest, opts ...grpc.CallOption) (*AnalyzeFrameResponse, error)
	DetectAccessEvent(ctx context.Context, in *DetectAccessEventRequest, opts ...grpc.CallOption) (*DetectAccessEventResponse, error)
}

type visionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVisionServiceClient(cc grpc.ClientConnInterface) VisionServiceClient {
	return &visionServiceClient{cc}
}

func (c *visionServiceClient) AnalyzeFrame(ctx context.Context, in *AnalyzeFrameRequest, opts ...grpc.CallOption) (*AnalyzeFrameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeFrameResponse)
	err := c.cc.Invoke(ctx, VisionService_AnalyzeFrame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visionServiceClient) DetectAccessEvent(ctx context.Context, in *DetectAccessEventRequest, opts ...grpc.CallOption) (*DetectAccessEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectAccessEventResponse)
	err := c.cc.Invoke(ctx, VisionService_DetectAccessEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VisionServiceServer is the server API for VisionService service.
// All implementations must embed UnimplementedVisionServiceServer
// for forward compatibility.
type VisionServiceServer interface {
	AnalyzeFrame(context.Context, *AnalyzeFrameRequest) (*AnalyzeFrameResponse, error)
	DetectAccessEvent(context.Context, *DetectAccessEventRequest) (*DetectAccessEventResponse, error)
	mustEmbedUnimplementedVisionServiceServer()
}

// UnimplementedVisionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVisionServiceServer struct{}

func (UnimplementedVisionServiceServer) AnalyzeFrame(context.Context, *AnalyzeFrameRequest) (*AnalyzeFrameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeFrame not implemented")
}
func (UnimplementedVisionServiceServer) DetectAccessEvent(context.Context, *DetectAccessEventRequest) (*DetectAccessEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetectAccessEvent not implemented")
}
func (UnimplementedVisionServiceServer) mustEmbedUnimplementedVisionServiceServer() {}
func (UnimplementedVisionServiceServer) testEmbeddedByValue()                       {}

// UnsafeVisionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VisionServiceServer will
// result in compilation errors.
type UnsafeVisionServiceServer interface {
	mustEmbedUnimplementedVisionServiceServer()
}

func RegisterVisionServiceServer(s grpc.ServiceRegistrar, srv VisionServiceServer) {
	// If the following call pancis, it indicates UnimplementedVisionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VisionService_ServiceDesc, srv)
}

func _VisionService_AnalyzeFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeFrameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisionServiceServer).AnalyzeFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisionService_AnalyzeFrame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisionServiceServer).AnalyzeFrame(ctx, req.(*AnalyzeFrameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisionService_DetectAccessEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectAccessEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisionServiceServer).DetectAccessEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisionService_DetectAccessEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisionServiceServer).DetectAccessEvent(ctx, req.(*DetectAccessEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VisionService_ServiceDesc is the grpc.ServiceDesc for VisionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VisionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vision.v1.VisionService",
	HandlerType: (*VisionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeFrame",
			Handler:    _VisionService_AnalyzeFrame_Handler,
		},
		{
			MethodName: "DetectAccessEvent",
			Handler:    _VisionService_DetectAccessEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vision/v1/vision.proto",
}
