// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: vision/v1/vision.proto

package visionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PersonId      string                 `protobuf:"bytes,1,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityResult) Reset() {
	*x = IdentityResult{}
	mi := &file_vision_v1_vision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityResult) ProtoMessage() {}

func (x *IdentityResult) ProtoReflect() protoreflect.Message {
	mi := &file_vision_v1_vision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityResult.ProtoReflect.Descriptor instead.
func (*IdentityResult) Descriptor() ([]byte, []int) {
	return file_vision_v1_vision_proto_rawDescGZIP(), []int{0}
}

func (x *IdentityResult) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *IdentityResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IdentityResult) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type AnalyzeFrameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frame         []byte                 `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"`
	CameraId      string                 `protobuf:"bytes,2,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	EdgeId        string                 `protobuf:"bytes,3,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeFrameRequest) Reset() {
	*x = AnalyzeFrameRequest{}
	mi := &file_vision_v1_vision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeFrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeFrameRequest) ProtoMessage() {}

func (x *AnalyzeFrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vision_v1_vision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeFrameRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeFrameRequest) Descriptor() ([]byte, []int) {
	return file_vision_v1_vision_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeFrameRequest) GetFrame() []byte {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *AnalyzeFrameRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *AnalyzeFrameRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

type AnalyzeFrameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Identities    []*IdentityResult      `protobuf:"bytes,2,rep,name=identities,proto3" json:"identities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeFrameResponse) Reset() {
	*x = AnalyzeFrameResponse{}
	mi := &file_vision_v1_vision_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeFrameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeFrameResponse) ProtoMessage() {}

func (x *AnalyzeFrameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vision_v1_vision_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeFrameResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeFrameResponse) Descriptor() ([]byte, []int) {
	return file_vision_v1_vision_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeFrameResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AnalyzeFrameResponse) GetIdentities() []*IdentityResult {
	if x != nil {
		return x.Identities
	}
	return nil
}

type AccessEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	CameraId      string                 `protobuf:"bytes,2,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	EdgeId        string                 `protobuf:"bytes,3,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessEvent) Reset() {
	*x = AccessEvent{}
	mi := &file_vision_v1_vision_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessEvent) ProtoMessage() {}

func (x *AccessEvent) ProtoReflect() protoreflect.Message {
	mi := &file_vision_v1_vision_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessEvent.ProtoReflect.Descriptor instead.
func (*AccessEvent) Descriptor() ([]byte, []int) {
	return file_vision_v1_vision_proto_rawDescGZIP(), []int{3}
}

func (x *AccessEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AccessEvent) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *AccessEvent) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *AccessEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AccessEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

type DetectAccessEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *AccessEvent           `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectAccessEventRequest) Reset() {
	*x = DetectAccessEventRequest{}
	mi := &file_vision_v1_vision_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectAccessEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectAccessEventRequest) ProtoMessage() {}

func (x *DetectAccessEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vision_v1_vision_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectAccessEventRequest.ProtoReflect.Descriptor instead.
func (*DetectAccessEventRequest) Descriptor() ([]byte, []int) {
	return file_vision_v1_vision_proto_rawDescGZIP(), []int{4}
}

func (x *DetectAccessEventRequest) GetEvent() *AccessEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type DetectAccessEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncidentId    string                 `protobuf:"bytes,1,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectAccessEventResponse) Reset() {
	*x = DetectAccessEventResponse{}
	mi := &file_vision_v1_vision_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectAccessEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectAccessEventResponse) ProtoMessage() {}

func (x *DetectAccessEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vision_v1_vision_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectAccessEventResponse.ProtoReflect.Descriptor instead.
func (*DetectAccessEventResponse) Descriptor() ([]byte, []int) {
	return file_vision_v1_vision_proto_rawDescGZIP(), []int{5}
}

func (x *DetectAccessEventResponse) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *DetectAccessEventResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_vision_v1_vision_proto protoreflect.FileDescriptor

const file_vision_v1_vision_proto_rawDesc = "" +
	"\n" +
	"\x16vision/v1/vision.proto\x12\tvision.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"e\n" +
	"\x0eIdentityResult\x12\x1b\n" +
	"\tperson_id\x18\x01 \x01(\tR\bpersonId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\"a\n" +
	"\x13AnalyzeFrameRequest\x12\x14\n" +
	"\x05frame\x18\x01 \x01(\fR\x05frame\x12\x1b\n" +
	"\tcamera_id\x18\x02 \x01(\tR\bcameraId\x12\x17\n" +
	"\aedge_id\x18\x03 \x01(\tR\x06edgeId\"p\n" +
	"\x14AnalyzeFrameResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x129\n" +
	"\n" +
	"identities\x18\x02 \x03(\v2\x19.vision.v1.IdentityResultR\n" +
	"identities\"\xb3\x01\n" +
	"\vAccessEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1b\n" +
	"\tcamera_id\x18\x02 \x01(\tR\bcameraId\x12\x17\n" +
	"\aedge_id\x18\x03 \x01(\tR\x06edgeId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"H\n" +
	"\x18DetectAccessEventRequest\x12,\n" +
	"\x05event\x18\x01 \x01(\v2\x16.vision.v1.AccessEventR\x05event\"T\n" +
	"\x19DetectAccessEventResponse\x12\x1f\n" +
	"\vincident_id\x18\x01 \x01(\tR\n" +
	"incidentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xc0\x01\n" +
	"\rVisionService\x12O\n" +
	"\fAnalyzeFrame\x12\x1e.vision.v1.AnalyzeFrameRequest\x1a\x1f.vision.v1.AnalyzeFrameResponse\x12^\n" +
	"\x11DetectAccessEvent\x12#.vision.v1.DetectAccessEventRequest\x1a$.vision.v1.DetectAccessEventResponseB*Z(vision-service/pkg/pb/vision/v1;visionv1b\x06proto3"

var (
	file_vision_v1_vision_proto_rawDescOnce sync.Once
	file_vision_v1_vision_proto_rawDescData []byte
)

func file_vision_v1_vision_proto_rawDescGZIP() []byte {
	file_vision_v1_vision_proto_rawDescOnce.Do(func() {
		file_vision_v1_vision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vision_v1_vision_proto_rawDesc), len(file_vision_v1_vision_proto_rawDesc)))
	})
	return file_vision_v1_vision_proto_rawDescData
}

var file_vision_v1_vision_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_vision_v1_vision_proto_goTypes = []any{
	(*IdentityResult)(nil),            // 0: vision.v1.IdentityResult
	(*AnalyzeFrameRequest)(nil),       // 1: vision.v1.AnalyzeFrameRequest
	(*AnalyzeFrameResponse)(nil),      // 2: vision.v1.AnalyzeFrameResponse
	(*AccessEvent)(nil),               // 3: vision.v1.AccessEvent
	(*DetectAccessEventRequest)(nil),  // 4: vision.v1.DetectAccessEventRequest
	(*DetectAccessEventResponse)(nil), // 5: vision.v1.DetectAccessEventResponse
	(*timestamppb.Timestamp)(nil),     // 6: google.protobuf.Timestamp
}
var file_vision_v1_vision_proto_depIdxs = []int32{
	0, // 0: vision.v1.AnalyzeFrameResponse.identities:type_name -> vision.v1.IdentityResult
	6, // 1: vision.v1.AccessEvent.occurred_at:type_name -> google.protobuf.Timestamp
	3, // 2: vision.v1.DetectAccessEventRequest.event:type_name -> vision.v1.AccessEvent
	1, // 3: vision.v1.VisionService.AnalyzeFrame:input_type -> vision.v1.AnalyzeFrameRequest
	4, // 4: vision.v1.VisionService.DetectAccessEvent:input_type -> vision.v1.DetectAccessEventRequest
	2, // 5: vision.v1.VisionService.AnalyzeFrame:output_type -> vision.v1.AnalyzeFrameResponse
	5, // 6: vision.v1.VisionService.DetectAccessEvent:output_type -> vision.v1.DetectAccessEventResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_vision_v1_vision_proto_init() }
func file_vision_v1_vision_proto_init() {
	if File_vision_v1_vision_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vision_v1_vision_proto_rawDesc), len(file_vision_v1_vision_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vision_v1_vision_proto_goTypes,
		DependencyIndexes: file_vision_v1_vision_proto_depIdxs,
		MessageInfos:      file_vision_v1_vision_proto_msgTypes,
	}.Build()
	File_vision_v1_vision_proto = out.File
	file_vision_v1_vision_proto_goTypes = nil
	file_vision_v1_vision_proto_depIdxs = nil
}
