// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: voice/v1/voice_recognition.proto

package voicerecognitionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VoiceRecognitionService_GetAudio_FullMethodName = "/voice_recognition.v1.VoiceRecognitionService/GetAudio"
)

// VoiceRecognitionServiceClient is the client API for VoiceRecognitionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoiceRecognitionServiceClient interface {
	GetAudio(ctx context.Context, in *GetAudioRequest, opts ...grpc.CallOption) (*GetAudioResponse, error)
}

type voiceRecognitionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoiceRecognitionServiceClient(cc grpc.ClientConnInterface) VoiceRecognitionServiceClient {
	return &voiceRecognitionServiceClient{cc}
}

func (c *voiceRecognitionServiceClient) GetAudio(ctx context.Context, in *GetAudioRequest, opts ...grpc.CallOption) (*GetAudioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAudioResponse)
	err := c.cc.Invoke(ctx, VoiceRecognitionService_GetAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoiceRecognitionServiceServer is the server API for VoiceRecognitionService service.
// All implementations must embed UnimplementedVoiceRecognitionServiceServer
// for forward compatibility.
type VoiceRecognitionServiceServer interface {
	GetAudio(context.Context, *GetAudioRequest) (*GetAudioResponse, error)
	mustEmbedUnimplementedVoiceRecognitionServiceServer()
}

// UnimplementedVoiceRecognitionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVoiceRecognitionServiceServer struct{}

func (UnimplementedVoiceRecognitionServiceServer) GetAudio(context.Context, *GetAudioRequest) (*GetAudioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAudio not implemented")
}
func (UnimplementedVoiceRecognitionServiceServer) mustEmbedUnimplementedVoiceRecognitionServiceServer() {
}
func (UnimplementedVoiceRecognitionServiceServer) testEmbeddedByValue() {}

// UnsafeVoiceRecognitionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoiceRecognitionServiceServer will
// result in compilation errors.
type UnsafeVoiceRecognitionServiceServer interface {
	mustEmbedUnimplementedVoiceRecognitionServiceServer()
}

func RegisterVoiceRecognitionServiceServer(s grpc.ServiceRegistrar, srv VoiceRecognitionServiceServer) {
	// If the following call pancis, it indicates UnimplementedVoiceRecognitionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VoiceRecognitionService_ServiceDesc, srv)
}

func _VoiceRecognitionService_GetAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAudioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceRecognitionServiceServer).GetAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceRecognitionService_GetAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceRecognitionServiceServer).GetAudio(ctx, req.(*GetAudioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VoiceRecognitionService_ServiceDesc is the grpc.ServiceDesc for VoiceRecognitionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoiceRecognitionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voice_recognition.v1.VoiceRecognitionService",
	HandlerType: (*VoiceRecognitionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAudio",
			Handler:    _VoiceRecognitionService_GetAudio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "voice/v1/voice_recognition.proto",
}
